### ISSUE TITLE
Error when getting cifields of a Cloud Identity Dynamic Group : ERROR: expected string or bytes-like object

### ISSUE THREAD

**Issue by LudovicEmo** [taers232c/GAMADV-XTD3#101]
Hi,

When we try to get the cifields on a dynamic group, we get the following error:
ERROR: expected string or bytes-like object
Could you please confirm that the feature is ok ?

For example:
$ gam info group french@ourdomain.com ciallfields
ERROR: expected string or bytes-like object

$gam info group technical_group_dynamic@ourdomain.com cifields dynamicgroupmetadata
ERROR: expected string or bytes-like object

Thanks in advance for your help.
Ludovic Emo
Accenture Google Workspace Deployment Architect

**Comment by taers232c** [comment]
Fixed 5.23.02
