### ISSUE TITLE
Piping command outputs to another command

### ISSUE THREAD

**Issue by Micko6816** [taers232c/GAMADV-XTD3#102]
Hi,

I'm currently trying to remove a user from all files inside a folder structure. I can easily pull the data with the following command:
gam user "owner" print filetree select "fileID" noindent fields id pm emailaddress "usertoremove"

This provides me with a list of ID's that the user has access to inside the folder structure, I know I can output that to a CSV and then run another command on that but I was wondering if I could pipe that into another gam command and remove the access, essentially merging both commands into one, as this is a common occurrence with our file structure.

I've looked into running the Automatic batch processing but this pipes the output of a command into the start of the other one, and removing file access requires me to input the ID not at the start.

**Comment by taers232c** [comment]
You can generate a CSV file more directly
See: https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Drive-Files-Display#file-selection-starting-point-for-display-file-list

Test getting file list
gam user "owner" print filelist select "fileID" fields id pm emailaddress "usertoremove" em
If you're happy with the result, then add
| gam csv - gam user "owner" delete drivefileacl "~id" "usertoremove"

**Comment by Micko6816** [comment]
Thanks, works like a treat.
