### ISSUE TITLE
BUG? gam print devices does not return some DeviceFieldName fields (encryptionState and osVersion)

### ISSUE THREAD

**Issue by richardwadsworth** [taers232c/GAMADV-XTD3#105]
Hi

The following call returns the requested device fields except `encryptionState` and `osVersion`.  These fields are simply not returned.

`gam print devices fields "deviceType, encryptionState, lastSyncTime, osVersion, ownerType, serialNumber" company nodeviceusers`

The API seems to support these fields and the GAM documentation suggests this is a valid call so wondering if this is an implementation bug?

What I'm actually trying to do is to determine it all company devices are encrypted and patched. I realise I can get these two fields (encryptionState and osVersion) from "`gam info device`" but it will take a very long time to make that call for every device rather than the one call to "`gam print devices`"

Version info
GAMADV-XTD3 5.24.03 - https://github.com/taers232c/GAMADV-XTD3 - pyinstaller
Ross Scroggs <ross.scroggs@gmail.com>
Python 3.8.6 64-bit final
google-api-python-client 1.9.3
httplib2 0.18.1
MacOS Catalina 10.15.7 x86_64

thanks

**Comment by taers232c** [comment]
Richard,

Call me on Hangouts/Meet/Zoom

Ross

ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Richard,

If you turn on debugging you'll see the request:
send: b'GET /v1/devices?customer=customers%2F04jtbf76&orderBy=&view=COMPANY_INVENTORY&fields=nextPageToken%2Cdevices%28serialNumber%2ClastSyncTime%2CosVersion%2CencryptionState%2Cname%2CdeviceType%2CownerType%29&pageSize=100&prettyPrint=true&alt=json H\
TTP/1.1\r\nHost: cloudidentity.googleapis.com\r\naccept: application/json\r\naccept-encoding: gzip, deflate\r\nuser-agent: GAMADV-XTD3 5.24.05 - https://github.com/taers232c/GAMADV-XTD3 / Ross Scroggs <ross.scroggs@gmail.com> / Python 3.8.6 final / mac\
OS-10.13.6-x86_64-i386-64bit x86_64 / (gzip)\r\nx-goog-api-client: gdcl/1.9.3 gl-python/3.8.6\r\ncontent-length: 0\r\nauthorization: Bearer \r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'

The fields you want are in the list but Google doesn't return their values.

**Comment by richardwadsworth** [comment]
Thanks Ross.  I'll see if I can get some API support from Google.  I'll close this ticket

**Comment by richardwadsworth** [comment]
hi Ross.

Just thought of something.  I just tried the same call without the `company` flag and this time it _does_ return the fields

This works
`gam print devices fields "deviceType, encryptionState, lastSyncTime, osVersion, ownerType, serialNumber" nodeviceusers`

This does _not_ work 
`gam print devices fields "deviceType, encryptionState, lastSyncTime, osVersion, ownerType, serialNumber" nodeviceusers company`

Rich

**Comment by taers232c** [comment]
Rich,

Did you get the fields for both company and personal devices or just personal.

> gam print devices fields "deviceType, encryptionState, lastSyncTime, osVersion, ownerType, serialNumber" nodeviceusers personal
> 
> 
Ross
--
ross.scroggs@gmail.com

**Comment by richardwadsworth** [comment]
hi Ross

I get the fields for both COMPANY and BYOD devices when no flag is used.  
I get the fields for BYOD when the `personal` flag is used.

I do not get the fields when the `company` flag is used.

**Comment by taers232c** [comment]
Richard,

The API claims that the fields are independent of ownership/view.

https://cloud.google.com/identity/docs/reference/rest/v1/devices/list
https://cloud.google.com/identity/docs/reference/rest/v1/devices#Device <https://cloud.google.com/identity/docs/reference/rest/v1/devices#Device>

Ross
--
ross.scroggs@gmail.com
