### ISSUE TITLE
Hard time understanding the Wiki

### ISSUE THREAD

**Issue by jjcasper** [taers232c/GAMADV-XTD3#107]
Good evening all!

I apologize for posting a question that is probably pretty simple to answer for others. I'm simply having a tough time understanding the Wiki. I thought I had GAM pretty well down. XTD3 just blows my mind. It's great, don't get me wrong. Thank you for it! It is just really hard to understand.

I also face issues like this:
~~~~~
Customer usage reports
Display customer usage data over a date range.

gam report usage customer [todrive <ToDriveAttribute>*]
        [startdate <Date>] [enddate <Date>] [range <Date> <Date>]
	[skipdates <Date>[:<Date>](,<Date>[:<Date>])*] [skipdaysofweek <DayOfWeek>(,<DayOfWeek>)*]
	[fields|parameters <String>]
The default enddate is today; the default startdate is 30 days prior to the enddate.

Example
Jay provided this example.

gam report usage customer parameters meet:total_call_minutes,meet:total_meeting_minutes start_date 2020-03-01 skipdaysofweek sat,sun todrive
~~~~~

The instructions say 'enddate' and 'startdate'. However, the example Jay provided shows them as 'start_date' with the underscore. 

Unfortunately, neither works. Here is what happens when I try a similar command.

C:\gamadv-xtd3>gam report customer parameters drive:num_items_viewed start_date 2020-10-01 todrive
Command: gam report customer parameters drive:num_items_viewed >>>start_date 2020-10-01<<< todrive

ERROR: Invalid argument
Help: Syntax in file C:\gamadv-xtd3\GamCommands.txt
Help: Documentation is at https://github.com/taers232c/GAMADV-XTD3/wiki

If I take start_date, startdate, etc out, it works.

What I'd like to do is this. What command would I use to print out a report that shows my users and the total storage they have? That's all I'd really like to do. If you can show me the one command, I should be to reverse-engineer other commands based on what you state.

Thank you very much for GAM, GAM Advanced, and for answering all our questions! Take care and have a great night!

Josh

**Comment by taers232c** [comment]
Josh,

You showed the syntax for "gam report usage customer" but issued the command "gam report customer"

Change: gam report customer parameters drive:num_items_viewed start_date 2020-10-01 todrive

To: gam report usage customer parameters drive:num_items_viewed start_date 2020-10-01 todrive

Ross
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Josh,

Do this to discover the latest data with data:
gam report usage user user user@domain.com  parameters "accounts:used_quota_in_mb" start_date -10d
Find the last date with data, then do to get data for all users
gam report usage user parameters "accounts:used_quota_in_mb" range 2020-11-14 2020-11-14

Ross

**Comment by jjcasper** [comment]
Hey Ross!

Thank you very much for writing back! I'm sure that will be it! Now that I have a good start forward, I'm sure I can figure things out.

Take care and have a great evening!

Josh
