### ISSUE TITLE
User Calendar Sync?

### ISSUE THREAD

**Issue by ShaunDarkLord** [taers232c/GAMADV-XTD3#108]
Hi

Is there a method for syncing a user's calendar?  I can see how to create individual events, but keeping track of this for a few thousand of my users looks like a bit of a challenge.

I couldn't see anything obvious in the Wiki or the API documentation, but I'm hoping I've just missed something, and there's some magic command for specifying a user, calendar name/id and a csv/ical file.

Thanks

**Comment by taers232c** [comment]
There is no magic.

I'm not completely clear on how sync would be implemented; what criteria would be used to add/delete events?

**Comment by ShaunDarkLord** [comment]
I was thinking that this could be used with a specific calendar just for syncing, and therefore the source csv/sheet/ical would be the definitive source.  Although an option to either sync or just add new events would probably be helpful (like the group sync options).

If I was just doing this for a few users, I think you've already provided all the tools I'd need;

- Print a users calendar
- Line by line, compare to the source calendar (for this I was just thinking of comparing the time, date and title).
- Add/Remove events as needed

However, I think with this approach, with each add/remove taking it's own API call, it would take days just for one sync.

**Comment by ShaunDarkLord** [comment]
Any thoughts on this?

**Comment by ShaunDarkLord** [comment]
Figured it out;
GAM redirect csv $Logfile multiprocess csv $RawSchCalFile gam user user@domain.com add event courses ~ID Summary ~Summary start ~Start end ~End location ~Location description ~Description
