### ISSUE TITLE
Command Options for Default Routing

### ISSUE THREAD

**Issue by zenjabba** [taers232c/GAMADV-XTD3#119]
I've been looking for the option to configure Default Routing https://support.google.com/a/answer/2368153?hl=en but have not been able to find it. I might have not looked hard enough or maybe there isn't an API endpoint to management it.

Thanks

**Comment by taers232c** [comment]
There is no API support for this as far as I know.

Ross

**Comment by zenjabba** [comment]
Sadly I think your correct...
