### ISSUE TITLE
Audit document views for large list of files

### ISSUE THREAD

**Issue by josh-mm** [taers232c/GAMADV-XTD3#122]
I know this can be done from the Google Security console, but I'm looking for a better way to automate this process. Can I feed a .csv into a GAMADV command that will then spit out the details on who viewed a file and when?

Thank you!

**Comment by taers232c** [comment]
Josh,

Send me a Meet invitation.

See: https://developers.google.com/admin-sdk/reports/v1/appendix/activity/drive
gam report drive filter "doc_id==12349Saovh-UUt65ovZdf3-yGqUxrwxyz" events view

Ross
