### ISSUE TITLE
Claim ownership - different domain

### ISSUE THREAD

**Issue by ffurrier** [taers232c/GAMADV-XTD3#123]
I have a problem with claiming ownership of files. 
There are two domains of our company, for example: a.com and sub.a.com
Most of the users are in the domain called a.com, except a few users, who are using the domain sub.a.com. 
I am the super admin of both domains, and both domains are under the same Google Workspace licence.
I am trying to claim the ownership all of the files under a specific folder tree, and received the message below for files owned by users in the sub.a.com domain:

```
User: drive@a.com, Claim Ownership 1 Drive File/Folder
  User: drive@a.com, Claim Ownership Drive File: *** (***)
    User: drive@a.com, Claim Ownership 1 User
      User: drive@a.com, Claim Ownership Not Performed 1 Drive File/Folder from User: someone@sub.a.com
        User: drive@a.com, Drive File: *** (***), Ownership Not Claimed: User: someone@sub.a.com in other domain.
```
        
The transfering ownership works well, but I don't want to claim ownership all of the file of the user someone@sub.a.com.
What can I do?

**Comment by taers232c** [comment]
GAM can only impersonate users in one domain at a time; to perform the claim GAM has to operate in two different domains; the fact that they are in the same account doesn't matter.

I'm in California, PST, send me a Meet invitation for between 8:00AM PST and 5:00PM PST and I'll help you.

Ross

**Comment by ffurrier** [comment]
Thanks for your help. It is a little bit complicated to organise the meet, i am in CET. I don't know when will i have time in the evening besides family.
Please, give me hints and i would try it myself first. The meet should be a the final option.
I need just a few words...

Should I create another project for the subdomain? (With multiple domain/client configurations? https://github.com/taers232c/GAMADV-XTD3/wiki/gam.cfg) 
I don't have admin user for sub.a.com, only for a.com. How can I register a new project without additional admin user in the domain @sub.a.com? How can I modify the domain setting in a project?

**Comment by taers232c** [comment]
The code is assumig that other domains are outside of Google, but that's not your situation.
I'm testing to see if your situation can be handled.

Who owns the top level folder, user@a.com <mailto:user@a.com> or user@sub.a.com <mailto:user@sub.a.com>?
What rights should user@sub.a.com <mailto:user@sub.a.com> have after the ownership change?

Ross
--
ross.scroggs@gmail.com

**Comment by ffurrier** [comment]
Shortly: 
 - the top level folder is owned by user@a.com
 - the role of the user@sub.a.com should be kept as "editor" (gam ... claim ownership ... keepuser)

In a wider view:
 - We have a common folder structure, which is owned by a technical user.
 - The normal users can create folders/files in the lower part of the folder structure according to their roles.
 - In a regular basis the ownership of all of the files is given to the technical user (thanks to gam).
 - After changing the ownership (with keepuser option) we clean up the permissions: if a user has a role through a group then we remove the user level permission.  (with a little python code, and using gam)
 - The user@sub.a.com is a "guest". The sub.a.com domain is maintained for "contractors". They have the same right to manipulate the content of the drive as a user in domain @a.com. They are members of the same groups in domain @a.com as normal users.
 - The files owned by users in @sub.a.com have to be claimed by the technical user after a while.

**Comment by taers232c** [comment]
This is very helpful, thank you.
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
The solution already exists; add the argument `subdomains sub.a.com`
See: https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Drive-Ownership#claim-ownership-of-files-that-other-users-own
```
$ gam user testsimple claim ownership 1w8aSt894jU4m0yOqr9iccW0Y5yA2d9Yp keepuser
User: testsimple@rdschool.org, Claim Ownership 1 Drive File/Folder
  User: testsimple@rdschool.org, Claim Ownership Drive Folder: ShareNet (1w8aSt894jU4m0yOqr9iccW0Y5yA2d9Yp)
    User: testsimple@rdschool.org, Claim Ownership 1 User
      User: testsimple@rdschool.org, Claim Ownership Not Performed 1 Drive File/Folder from User: testuser1@rdschool.net
        User: testsimple@rdschool.org, Drive File: NetDoc (1LJHIw35f_eQt3-9PFGsFOomJao9HEQxM8istHDYhKJ4), Ownership Not Claimed: User: testuser1@rdschool.net in other domain.

$ gam user testsimple claim ownership 1w8aSt894jU4m0yOqr9iccW0Y5yA2d9Yp keepuser subdomains rdschool.net
User: testsimple@rdschool.org, Claim Ownership 1 Drive File/Folder
  User: testsimple@rdschool.org, Claim Ownership Drive Folder: ShareNet (1w8aSt894jU4m0yOqr9iccW0Y5yA2d9Yp)
    User: testsimple@rdschool.org, Claim Ownership 1 User
      User: testsimple@rdschool.org, Claim Ownership 1 Drive File/Folder from User: testuser1@rdschool.net
        User: testsimple@rdschool.org, Drive File: NetDoc (1LJHIw35f_eQt3-9PFGsFOomJao9HEQxM8istHDYhKJ4), Ownership Claimed from User: testuser1@rdschool.net
        User: testuser1@rdschool.net, Drive File: NetDoc (1LJHIw35f_eQt3-9PFGsFOomJao9HEQxM8istHDYhKJ4), Role: writer, Retained
```

**Comment by ffurrier** [comment]
It's embarassing. Thanks for help.
