### ISSUE TITLE
Splitting a fileinfo query into separate processes?

### ISSUE THREAD

**Issue by poseyjmac** [taers232c/GAMADV-XTD3#124]
I use this line:

$Folder_Info = gam user $User show fileinfo my_files

in my powershell backup script to get detailed info for files including 'date modified', which I can then apply later to downloaded files.

This works great for 99% of the users. The problem is the time it takes with 1% of the users having thousands of files. It's like trying to get an ocean of file attributes through a garden hose from Google, and it takes days to complete a full transfer of file data + the files. Downloading the actual files is very fast in comparison.

My question is, can I widen this garden hose from Google by splitting this query into separate lines to get me this data in less time? I could then parse the data in multiple variables separately. 

My first idea was using the 'filenamematchpattern' option with a regular expression, where I'd say: give me all files starting with a-m, then another query with all folders except for those, giving me a complete set. Not elegant, but it would at least be a little better. It doesn't seem to work with 'show fileinfo', though.

**Comment by taers232c** [comment]
Send me a Meet invitation.

**Comment by taers232c** [comment]
Why are you using show fileinfo? print filelist would give you easier to parse data.
Suppose you have a CSV file (Users.csv) full of email addresses with header primaryEmail.
The following commands will process `gam.cfg num_threads` users in parallel.
This will give you a CSV file per user.
```
gam csv Users.csv gam redirect csv  "~~primaryEmail~~.csv" user "~primaryEmail" print filelist fields id,name,...
```

This will give you a TXT file per user.
```
gam csv Users.csv gam redirect stdout  "~~primaryEmail~~.txt" user "~primaryEmail" show fileinfo my-files fields id,name,...
```

**Comment by poseyjmac** [comment]
Good question, lol. So, 'print filelist' takes seconds as opposed to days with 'show fileinfo'. 'show fileinfo' should be ashamed of itself. Thanks, Ross.
