### ISSUE TITLE
Deleted classes not being deleted

### ISSUE THREAD

**Issue by ShaunNeighbourSwale** [taers232c/GAMADV-XTD3#13]
Hi

Classes that have been deleted using "gam delete course <CourseID>" are still appearing when executing "GAM print courses".  This would be a minor inconvenience, but this prevents "GAM print courses alias" as when GAM gets to one of the deleted classes it returns "ERROR: 404: notFound - Requested entity was not found."

**Comment by ShaunNeighbourSwale** [comment]
This has been tested with latest version (4.86.06)

**Comment by taers232c** [comment]
You might ask Google why they're returning a deleted course in the list of courses.
I'm adding code to handle this case, it will be ready later this morning.

**Comment by taers232c** [comment]
Try 4.86.07

**Comment by ShaunNeighbourSwale** [comment]
Beautiful!  Working as it used to now! (Was working fine last Sunday with the same deleted classes)  Thank you so much!

I've already logged a ticked with the G-suite Dev Team.  They're regular support guys were a bit confused by the issue.

**Comment by taers232c** [comment]
Call me on Google Hangouts

ross.scroggs@gmail.com
