### ISSUE TITLE
error with report for all users

### ISSUE THREAD

**Issue by msizec** [taers232c/GAMADV-XTD3#14]
Hello
I have an error with this command (the same with drive report)

![image](https://user-images.githubusercontent.com/29256398/59683702-f3c13600-91d8-11e9-9235-907ad7ae6427.png)

**Comment by taers232c** [comment]
I'll fix this morning.

Ross
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Fixed 4.86.09

**Comment by msizec** [comment]
thx
tested => ok
