### ISSUE TITLE
Add the ability to see 2nd- and 3rd-last user

### ISSUE THREAD

**Issue by sorentorp** [taers232c/GAMADV-XTD3#148]
To make it easier to solve supportcases in a non 1:1 environment, it would make great sense to expand the recentUser to include 2nd- and 3rd-last user.

I think it should be options to add both in GAM exports, so maybe "recentUser", "recentUser2" and "recentUser3" would be good option-names.

It is possible to get the data from Google - it can be done like this, in GAS.
var recentUsersEmail_0 = (device && device.recentUsers && device.recentUsers[0] && device.recentUsers[0].email)
var recentUsersEmail_1 = (device && device.recentUsers && device.recentUsers[1] && device.recentUsers[1].email)
var recentUsersEmail_2 = (device && device.recentUsers && device.recentUsers[2] && device.recentUsers[2].email)

Hope you like my idea :-D

**Comment by taers232c** [comment]
This capability already exists.
Compare:
gam print cros recentusers listlimit 3
gam print cros recentusers listlimit 3 onerow

See: https://github.com/taers232c/GAMADV-XTD3/wiki/ChromeOS-Devices#print-a-header-row-and-fields-for-selected-cros-devices

**Comment by sorentorp** [comment]
hmm, I cant seem to get it to work. But command is like this.

`gam config csv_output_row_filter "'^status$:regex:active'" redirect csv - multiprocess todrive tdfileid 1qE-o52yek0-xxxxxxxxxxxxxxxxxxxxxxxxx tdtitle "xxxx_xxx_INFO" tdsheet Devices_GAM tdupdatesheet true print cros fields ou,serialNumber,osversion,annotatedassetid,lastenrollmenttime,annotatedlocation,lastSync,model,recentusers,status listlimit 3`

**Comment by taers232c** [comment]
You omitted the onerow parameter; add it to the end.

Ross
--
***@***.***

**Comment by sorentorp** [comment]
Ahh, that worked perfect! Thank you
