### ISSUE TITLE
Importing New Domain shared Contacts - Syntax Help Required

### ISSUE THREAD

**Issue by wicknet** [taers232c/GAMADV-XTD3#15]
Kudos on extending Gam to handle this very useful feature. We have 615 domain shared contacts imported by a consultant 3 years ago that I can list using "gam info contacts". I've read through the docs but could not make any headway in deleting those and importing a fresh list. Hoping some can provide "simple" instructions to:
1. bulk delete all these 615 shared contacts in one swoop
2. import a new list of 384 current contacts in a csv - we only need 3 columns - firstname, lastname and email ID (belonging to another trusted domain). Actual syntax would be helpful for importing just one contact with only these 3 attributes - I can then batch gam it for the rest.

Any help would be deeply  appreciated. Thanks!

**Comment by taers232c** [comment]
Delete old contacts
```
gam print contacts > OldContacts.csv
gam csv OldContacts.csv gam delete contact ~ContactID
```
Make a single new contact
```
gam create contact firstname Jim lastname Smith email work jsmith@newdomain.com primary
```
Many many new contacts
```
NewContacts.csv
firstname,lastname,email
Jim,Smith,jsmith@newdomain.com
Mary,Jones,mjones@newdomain.com
...
gam csv NewContacts.csv gam create contact firstname ~firstname lastname ~lastname email work ~email primary
```

**Comment by wicknet** [comment]
Thank you SO much! Your prompt help is very much appreciated.

Your hard work in developing this solution will save us (and others) a ton of time and $$ in managing shared domain contacts.

If I can contribute any material help for this project, do let me know!
