### ISSUE TITLE
get drivefile format microsoft

### ISSUE THREAD

**Issue by ffurrier** [taers232c/GAMADV-XTD3#160]
I would like to make a backup of my files stored in Google Drive. Most of the files don't need any conversion, except the type of gsheet and gdoc. I prefer microsoft format for this type of files. So I use this command:
gam user ~owner get drivefile id ~id  targetfolder "~~exportPath~~" showprogress overwrite format microsoft

I have problem with the files having mime type of 'application/x-zip' and 'application/octet-stream'.
**The name of the downloaded files will have an extension ".docx". Why?**
The content of the files seems to be OK.

**Comment by ffurrier** [comment]
The name of the file in Google Drive: something.zip.001

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation

Ross

**Comment by taers232c** [comment]
Here's what I get:

```
$ gam user testsimple get drivefile 12gRR9vkOfJwkw3NJIW-M5Qb_toYIr3d1 showprogress overwrite format microsoft
User: testsimple@rdschool.org, Download 1 Drive File
  User: testsimple@rdschool.org, Drive File: foo.zip.001, Downloaded: 100.00%
  User: testsimple@rdschool.org, Drive File: foo.zip.001, Downloaded to: /Users/admin/Documents/GoogleApps/GAM3/Sandbox/foo.zip.001.zip, Size: 1kb
```

What is your GAM version?

Show an example.

Thanks

**Comment by ffurrier** [comment]
I'am in a different time zone, it would be hard to organize a meeting.
I have 6.04.04 (latest) version of gam.
I use 7Zip to compress and slice my files. After the compression and uploading the files I have these pairs of names and mime types:

- A.zip.001, application/x-zip
- A.zip.002, application/octet-stream
- A.zip.003, application/octet-stream
- A.zip.004, application/octet-stream

I think the mime type is the key.
**After downloading I would like to have the same file name I uploaded before.**  Except the mime types of application/vnd.google-apps.*, which could be converted to microsoft format.

- I could call different gam command for "google-apps" to convert only these mime types, but leaving the option "format microsoft" doesn't solve the problem: the zipped files will have the extension .odp instead of .docx without format option.
- I' ve tried to add a definit file name with option "targetname", but i have the same result: files with .odp extension.


Examples:

c:\Temp>gam user drive@x.y get drivefile id XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX targetfolder "c:\temp" overwrite showprogress format microsoft
User: drive@x.y, Download 1 Drive File
  User: drive@x.y, Drive File: A.zip.001, Downloaded:  10.00%
  ...
  User: drive@x.y, Drive File: A.zip.001, Downloaded: 100.00%
  User: drive@x.y, Drive File: A.zip.001, Downloaded to: c:\temp\A.zip.001.docx, Size: 1gb

c:\Temp>gam user drive@x.y get drivefile id YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY targetfolder "c:\temp" overwrite showprogress format microsoft
User: drive@x.y, Download 1 Drive File
  User: drive@x.y, Drive File: A.zip.002, Downloaded:  10.00%
  ...
  User: drive@x.y, Drive File: A.zip.002, Downloaded: 100.00%
  User: drive@x.y, Drive File: A.zip.002, Downloaded to: c:\temp\A.zip.002.docx, Size: 1gb

c:\Temp>gam user drive@x.y get drivefile id XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX targetfolder "c:\temp" overwrite showprogress
User: drive@x.y, Download 1 Drive File
  User: drive@x.y, Drive File: A.zip.001, Downloaded:  10.00%
  ...
  User: drive@x.y, Drive File: A.zip.001, Downloaded: 100.00%
  User: drive@x.y, Drive File: A.zip.001, Downloaded to: c:\temp\A.zip.001.odp, Size: 1gb

c:\Temp>gam user drive@x.y get drivefile id YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY targetfolder "c:\temp" overwrite showprogress
User: drive@x.y, Download 1 Drive File
  User: drive@x.y, Drive File: A.zip.002, Downloaded:  10.00%
  ...
  User: drive@x.y, Drive File: A.zip.002, Downloaded: 100.00%
  User: drive@x.y, Drive File: A.zip.002, Downloaded to: c:\temp\A.zip.002.odp, Size: 1gb

c:\Temp>gam user drive@x.y get drivefile id XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX targetfolder "c:\temp" targetname "A.zip.001" overwrite showprogress
User: drive@x.y, Download 1 Drive File
  User: drive@x.y, Drive File: A.zip.001, Downloaded:  10.00%
  ...
  User: drive@x.y, Drive File: A.zip.001, Downloaded: 100.00%
  User: drive@x.y, Drive File: A.zip.001, Downloaded to: c:\temp\A.zip.001.odp, Size: 1gb

c:\Temp>gam user drive@x.y get drivefile id YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY targetfolder "c:\temp" targetname "A.zip.002" overwrite showprogress
User: drive@x.y, Download 1 Drive File
  User: drive@x.y, Drive File: A.zip.002, Downloaded:  10.00%
  ...
  User: drive@x.y, Drive File: A.zip.002, Downloaded: 100.00%
  User: drive@x.y, Drive File: A.zip.002, Downloaded to: c:\temp\A.zip.002.odp, Size: 1gb

**Comment by taers232c** [comment]
```
$ gam user testsimple show fileinfo 12gRR9vkOfJwkw3NJIW-M5Qb_toYIr3d1 fields id,name,fileextension,fullfileextension,mimetype
User: testsimple@rdschool.org, Show 1 Drive File/Folder
  Drive File: foo.zip.001 (12gRR9vkOfJwkw3NJIW-M5Qb_toYIr3d1)
    fileExtension: zip
    fullFileExtension: zip
    id: 12gRR9vkOfJwkw3NJIW-M5Qb_toYIr3d1
    mimeType: application/zip
    name: foo.zip.001

```

Do this for A.zip.001 and A.zip.002

**Comment by taers232c** [comment]
Try 6.04.05.

**Comment by ffurrier** [comment]
It is OK now. Thanks.
