### ISSUE TITLE
transferring all user's folders from root to a team drive

### ISSUE THREAD

**Issue by Mearman** [taers232c/GAMADV-XTD3#175]
Not sure if I'm missing something but I can't see a straightforward way to transfer all of a users files to a teamdrive?

Currently my process is:

get all files from root
```
gam user user.name@domain.com print filelist query "'root' in parents and trashed=false"
```

parse and format that list to make a set of commands with the following format:
```
gam user user.name@domain.com move drivefile EACH_ROOT_ITEM teamdriveparentid DESTINATION_TD
```
this method works, but it seems like there must be a more straightforward way?

---

ideally, essentially what I'm trying to achieve is:
```
gam user user.name@domain.com move ALL_DRIVE_ITEMS teamdriveparentid DESTINATION_TD/user.name

```

**Comment by taers232c** [comment]
Joseph,

Read this: https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Drive-Copy-Move#move-files-and-folders <https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Drive-Copy-Move#move-files-and-folders>

Start from here:
> gam user ***@***.*** move drivefile root mergewithparent true teamdriveparentid DESTINATION_TD/user.name
Ross
--
***@***.***
