### ISSUE TITLE
"gam print resoldsubscriptions" uses default maxResults value (20 subscriptions/page)

### ISSUE THREAD

**Issue by jay-eleven** [taers232c/GAMADV-XTD3#183]
Hi Ross!

While playing around with the `resoldsubscriptions` command, I was curious to see if **gam** was setting the `maxResults` parameter.

According to the [Google Workspace Reseller API / Method: subscriptions.list documentation](https://developers.google.com/admin-sdk/reseller/reference/rest/v1/subscriptions/list?apix_params=%7B%22maxResults%22%3A100%7D#:~:text=maxResults,default%20is%2020.):

```
maxResults
integer (uint32 format)
When retrieving a large list, the maxResults is the maximum number of results per page.
The nextPageToken value takes you to the next page.
The default is 20.
```
Let's check:
```
jay@cloudshell:~$ gam config debug_level 1 redirect csv subs print resoldsubscriptions > debug
jay@cloudshell:~$ cat debug | grep "GET /apps/reseller/v1/subscriptions" --max-count=1 | awk '{print $3}'
/apps/reseller/v1/subscriptions?fields=nextPageToken%2Csubscriptions&prettyPrint=true&alt=json
```
`maxResults` doesn't seem to be set. Let's check the default value:
```
jay@cloudshell:~$ cat subs | grep "customerId,skuId" --invert-match | wc --lines
205
jay@cloudshell:~$ cat debug | grep "GET /apps/reseller/v1/subscriptions" | wc --lines
11
```
11 * **20** = 220 > 205. Sounds about right.

The `/apps/reseller/v1/subscriptions` endpoint allows the `maxResults` parameter to be in the range 1 - 100:

```
{
  "error": {
    "code": 400,
    "message": "Invalid value '101'. Values must be within the range: [value: 1\n, value: 100\n]",
    "errors": [
      {
        "message": "Invalid value '101'. Values must be within the range: [value: 1\n, value: 100\n]",
        "domain": "global",
        "reason": "invalidParameter"
      }
    ]
  }
}
```
Would it be possible to add `maxResults=100` when calling the endpoint to make 5x less API calls?
IMHO, adding a config option to `gam.cfg` (`subscriptions_max_results`) like other commands have (`member_max_results`, `mobile_max_results`, `message_max_results`...) might be overkill since `maxResults` range is so small (1-100) and most probably you'll set it to 100 in `[DEFAULT]`. 🤷‍♂

**Comment by taers232c** [comment]
Jay,

Done. https://github.com/taers232c/GAMADV-XTD3/wiki/GamUpdates <https://github.com/taers232c/GAMADV-XTD3/wiki/GamUpdates>

I'd change this:
> gam config debug_level 1 redirect csv subs print resoldsubscriptions > debug
to this:
> gam config debug_level 1 redirect stdout debug redirect csv subs print resoldsubscriptions
This gets you ready to do this:
gam redirect stdout userinfo.txt multiprocess csv users.csv gam info user "~primaryEmail"

Ross
--
***@***.***

**Comment by jay-eleven** [comment]
Ross,

Thanks! Works like a charm!

```
jay@cloudshell:~$ ./updategam.sh 
...
GAMADV-XTD3 6.07.17 - https://github.com/taers232c/GAMADV-XTD3 - pyinstaller
...
GAM upgrade complete!
jay@cloudshell:~$ gam config debug_level 1 redirect stdout debug redirect csv subs print resoldsubscriptions
jay@cloudshell:~$ cat gam_downloads/debug | grep "GET /apps/reseller/v1/subscriptions" --max-count=1 | awk '{print $3}'
/apps/reseller/v1/subscriptions?fields=nextPageToken%2Csubscriptions&maxResults=100&prettyPrint=true&alt=json
```
