### ISSUE TITLE
Expose "Management Type" in Cloud-Identity-Devices

### ISSUE THREAD

**Issue by richardwadsworth** [taers232c/GAMADV-XTD3#191]
Hi Ross

Is is possible to expose a device's management type in `gam print devices` and `gam info device` as a [DeviceFieldName](https://github.com/taers232c/GAMADV-XTD3/wiki/Cloud-Identity-Devices#definitions)

where `<DeviceManagementType> ::= Drive for desktop | Endpoint Verification | Enhanced desktop security | GCPW | Fundamental`

To be able to filter on this would be excellent too.

thanks

**Comment by taers232c** [comment]
Richard,

Send me a Meet/Zoom invitation. I'm in California (PDT)

ross.scroggs @ gmail.com

**Comment by taers232c** [comment]
Here is the API documentation: https://cloud.google.com/identity/docs/reference/rest/v1/devices#Device
Which field is the device management type?

**Comment by richardwadsworth** [comment]
Hi Ross

Looking at the documentation it appears that the "management type" **is not exposed via the API**.  I'll raise it with Google support and come back if and when they add it.

thanks
