### ISSUE TITLE
DeprecationWarning python 3.7.1

### ISSUE THREAD

**Issue by lerklompen** [taers232c/GAMADV-XTD3#2]
Python 3.7.1 64-bit final (on Mac):

I get these warnings on all commands:
gam.py:2303: DeprecationWarning: 'U' mode is deprecated
  with open(fileName, u'rU') as f:
gam.py:2304: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(f)

It seems to work fine if I change to this:
2303      with open(fileName, u'r') as f:
2304        config.read_file(f)

/Mattias

**Comment by taers232c** [comment]
Mattias,

Thanks. There are two other cases where 'rU' should be changed to 'r'. I updated the project with all three changes. I did not change the version.

Ross
