### ISSUE TITLE
Wrong license name for Legacy Free SKU id 

### ISSUE THREAD

**Issue by jay-eleven** [taers232c/GAMADV-XTD3#200]
Hi Ross!

Turns out Google has NOT rebranded the legacy free G Suite SKUs to Workspace:

```
  "items": [
    {
      "kind": "licensing#licenseAssignment",
      "productId": "Google-Apps",
      "selfLink": "https://content-licensing.googleapis.com/apps/licensing/v1/product/Google-Apps/sku/Google-Apps/user/zzzzz",
      "skuId": "Google-Apps",
      "skuName": "G Suite legacy",
      "productName": "Google Workspace"
    },...
```

`gam` calls this SKU `Google Workspace Free/Standard` when it should call it just `G Suite legacy` like Google does. AFAIK, G Suite legacy SKU is documented nowhere, I just happen to have access to one.

`gam` [docs](https://github.com/taers232c/GAMADV-XTD3/wiki/Licenses#:~:text=Google%20Workspace%20Free/Standard,standard) would also need to be changed, but I can do that for you when this issue is solved **IF** you decide to change it. This is by no means necessary, but I thought it'd be nice to have a 1:1 relation between Google and `gam` terminology. 🤓

PS: there might be a reason why `gam` refers to this SKU the way it does, IDK 🤷‍♂

**Comment by taers232c** [comment]
Updated in 6.08.09
--
***@***.***

**Comment by jay-eleven** [comment]
Fixed!

Thanks Ross!
