### ISSUE TITLE
Update USer Custom Schema Values

### ISSUE THREAD

**Issue by dav1303** [taers232c/GAMADV-XTD3#201]
Hi
When I try to do this command which works perfectly a couple of days ago

gam update user xxxx Profil_Metier.Frame '"sssss"

I get this error
User: david_lazaro_1@xxxx.com, Update Failed: Invalid Schema Value

Can you help ?

The debug gives me that and my field is multivalued

ERROR:  JSON: {'error': {'code': 400, 'message': 'Invalid Input: custom_schema', 'errors': [{'message': 'Invalid Input: custom_schema', 'domain': 'global', 'reason': 'invalid'}]}}

thanks

**Comment by taers232c** [comment]
Show this.
gam info schema Profil_Metier

Ross
--
***@***.***
