### ISSUE TITLE
Permission error when trying to print/update devices

### ISSUE THREAD

**Issue by GustavJer** [taers232c/GAMADV-XTD3#206]
Hi! Im having som trouble with the commands relating to devices.
When I run `gam print devices` I get the following error:

```
Getting all Devices, may take some time on a large Google Workspace Account...
Device Print Failed: The caller does not have permission
name
```
I also get the same error if I try `gam sync devices csvfile $FileFullPath`.

Some info about my GAM-installation:
```
gam help

GAMADV-XTD3 6.08.03 - https://github.com/taers232c/GAMADV-XTD3 - pyinstaller
Ross Scroggs <ross.scroggs@gmail.com>
Python 3.9.7 64-bit final
Windows 10 10.0.14393 SP0 Multiprocessor Free AMD64
Path: C:\GAMADV-XTD3
Config File: C:\GamCFG\gam.cfg, Section: DEFAULT, customer_id: , domain: 
Help: Syntax in file C:\GAMADV-XTD3\GamCommands.txt
Help: Documentation is at https://github.com/taers232c/GAMADV-XTD3/wiki
```
I´ve tried/checked the following:

- Updated the project with `gam update project`
- Updated client access with `gam oauth update`
- Checked service account access and I have a PASS on all scopes

**Comment by taers232c** [comment]
I'm in California (PDT), send me a Meet/Zoom invitation.

Ross
ross.scroggs @ gmail.com

**Comment by GustavJer** [comment]
Hi,

Just checked with the 6.08.28 version and I still get the same error.

**Comment by taers232c** [comment]
I'm in California (PDT), I'll be available after 7:45AM for a Meet/Zoom call.

Ross
--
***@***.***

**Comment by GustavJer** [comment]
Hi again,

I actually solved this by just filling in the customer_id in my gam.cfg file for the domains I have. After this it works!

Gustav
