### ISSUE TITLE
ValueError on install of 6.08.21

### ISSUE THREAD

**Issue by genecheek** [taers232c/GAMADV-XTD3#212]
When I get to the auth it looks like it goes through but I get a clock error with anything I trey to run. 

Select the authorized scopes by entering a number.
Append an 'r' to grant read-only access or an 'a' to grant action-only access.

[*]  0)  Calendar API (supports readonly)
[*]  1)  Chrome Browser Cloud Management API (supports readonly)
[*]  2)  Chrome Management API - read only
[*]  3)  Chrome Policy API (supports readonly)
[*]  4)  Chrome Version History API
[*]  5)  Classroom API - Course Announcements (supports readonly)
[*]  6)  Classroom API - Course Topics (supports readonly)
[*]  7)  Classroom API - Course Work/Materials (supports readonly)
[*]  8)  Classroom API - Course Work/Submissions (supports readonly)
[*]  9)  Classroom API - Courses (supports readonly)
[*] 10)  Classroom API - Profile Emails
[*] 11)  Classroom API - Profile Photos
[*] 12)  Classroom API - Rosters (supports readonly)
[*] 13)  Classroom API - Student Guardians (supports readonly)
[*] 14)  Cloud Identity Groups API (supports readonly)
[*] 15)  Cloud Storage (Vault Export - read only)
[*] 16)  Contact Delegation API (supports readonly)
[*] 17)  Contacts API - Domain Shared and Users and GAL
[*] 18)  Data Transfer API (supports readonly)
[*] 19)  Directory API - Chrome OS Devices (supports readonly)
[*] 20)  Directory API - Customers (supports readonly)
[*] 21)  Directory API - Domains (supports readonly)
[*] 22)  Directory API - Groups (supports readonly)
[*] 23)  Directory API - Mobile Devices Directory (supports readonly and action)
[*] 24)  Directory API - Organizational Units (supports readonly)
[*] 25)  Directory API - Printers (supports readonly)
[*] 26)  Directory API - Resource Calendars (supports readonly)
[*] 27)  Directory API - Roles (supports readonly)
[*] 28)  Directory API - User Schemas (supports readonly)
[*] 29)  Directory API - User Security
[*] 30)  Directory API - Users (supports readonly)
[*] 31)  Groups Migration API
[*] 32)  Groups Settings API
[*] 33)  License Manager API
[*] 34)  People API (supports readonly)
[*] 35)  People Directory API - read only
[*] 36)  Pub / Sub API
[*] 37)  Reports API - Audit Reports
[*] 38)  Reports API - Usage Reports
[*] 39)  Reseller API
[*] 40)  Site Verification API
[*] 41)  Sites API
[*] 42)  Vault API (supports readonly)

     s)  Select all scopes
     u)  Unselect all scopes
     e)  Exit without changes
     c)  Continue to authorization
Please enter 0-42[a|r] or s|u|e|c: c

Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=953057726403-g9en0udl0ou9s36ubpj5r83s7c4u2tnb&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.device.chromebrowsers+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fchrome.management.reports.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fchrome.management.policy++https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.announcements+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.topics+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.courseworkmaterials+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.coursework.students+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.courses+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.profile.emails+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.profile.photos+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.rosters+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.guardianlinks.students+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-identity.groups+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_only+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.contact.delegation+https%3A%2F%2Fwww.google.com%2Fm8%2Ffeeds+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.datatransfer+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.device.chromeos+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.customer+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.domain+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.group+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.device.mobile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.orgunit+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.chrome.printers+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.resource.calendar+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.rolemanagement+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.userschema+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.user.security+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.user+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fapps.groups.migration+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fapps.groups.settings+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fapps.licensing+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdirectory.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpubsub+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.reports.audit.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.reports.usage.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fapps.order+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification+https%3A%2F%2Fsites.google.com%2Ffeeds+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fediscovery&state=RkO35SXDWkni46PNd9I9YDwFuT9Zlk&access_type=offline&login_hint=gcheek%40schnucks.com&code_challenge=t3-ffOaxK9JsHnb5knQEHKqywZ31XRk_SQ1iyNKc18o&code_challenge_method=S256

If your browser is on a different machine then press CTRL+C,
set no_browser = true in gam.cfg and re-run this command.

Traceback (most recent call last):
  File "__init__.py", line 58089, in ProcessGAMCommand
  File "__init__.py", line 57204, in processOauthCommands
  File "__init__.py", line 8887, in doOAuthCreate
  File "__init__.py", line 8854, in doOAuthRequest
  File "__init__.py", line 3924, in writeClientCredentials
  File "__init__.py", line 3904, in _getValueFromOAuth
  File "google\oauth2\id_token.py", line 144, in verify_oauth2_token
  File "google\oauth2\id_token.py", line 124, in verify_token
  File "google\auth\jwt.py", line 278, in decode
  File "google\auth\jwt.py", line 195, in _verify_iat_and_exp
ValueError: Token used too early, 1634244631 < 1634244633. Check that your computer's clock is set correctly.

C:\GAMADV-XTD3>

**Comment by taers232c** [comment]
Gene,

I'll be available to Meet/Zoom this moring after 8:45; send an invitation for then.

Ross
--
***@***.***

**Comment by genecheek** [comment]
https://meet.google.com/ybx-etpy-diz?authuser=0
