### ISSUE TITLE
Gam upgrade from 5.24  to 6.08   cause issues with external contacts management. 

### ISSUE THREAD

**Issue by ericwhiteau** [taers232c/GAMADV-XTD3#219]
I am upgrading an existing airflow server that has gam embedded in scheduled tasks to manage add and delete of GAL contacts.

the upgrade was for airflow V1  to V2.  however, I updated gam at the same time.  I had a fail on all GAL-related tasks and blamed Airflow.  However, I have done some testing and its the newer version of gam.   all the config data is the same.  and moving the executable back to the older  version allows it to start working.

Symptoms.
Create gal was not working.   (process checks gals against user list and adds new ones.  Process said it was successful, however, rerun will try to create the same "New contacts")   Delete by ID reports they are not there....
Delete gal was not working.   as above delete gal  by id fails.    See below 

-----------------------------------------
default@3465947a336d:~$ gam --version
GAMADV-XTD3 6.08.03 - https://github.com/taers232c/GAMADV-XTD3 - pyinstaller
Ross Scroggs <ross.scroggs@gmail.com>
Python 3.9.7 64-bit final
Linux Debian 10 Buster x86_64
Path: /usr/local/bin
Config File: /opt/airflow/.gam/gam.cfg, Section: DEFAULT, customer_id: my_customer, domain: 

gam select <dom>   show gal emailmatchpattern axxx.hxxx@yyyy.com     # (created in v5 to get the ID.  as C.38xxx is useless)
Contact: C.389c540e94a57a64 (5479/5480)
    Updated: 2021-11-26T07:28:02.941Z
    Name: Axxx Hxxx
    Given Name: Axxx
    Family Name: Hxxx
    Emails:
      type: work
        rank: primary
        address: axxx.hxxx@yyyy.com
		
default@3465947a336d:~$ gam select "targetDom" delete contact 20d6d3be8a52a2b8
Domain:, Delete maximum of 1 Contact
  Domain:, Contact: 20d6d3be8a52a2b8, Delete Failed: Does not exist

airflow@9db95ddb3806:~$ gam --version
GAMADV-XTD3 5.24.03 - https://github.com/taers232c/GAMADV-XTD3 - pyinstaller

airflow@9db95ddb3806:~$ gam select "targetDom"  delete contact 20d6d3be8a52a2b8
Domain: yyy.com.au, Delete maximum of 1 Contact
  Domain: "targetDom".com.au, Contact: 20d6d3be8a52a2b8, Deleted

I will push forward with my upgrade but use the 5.24 for the moment.

Please let me know if I have messed up the install some how,  but I can switch the bin/gam back and forward with out changing anything else and get the pass fail.

thanks in advance.

PS  Gam is doing a great job other than that.   :-)

**Comment by ericwhiteau** [comment]
Note:  my bracketed comment on the show gal emailmatchpattern  line.

It doesnt seem to work in either version  to query   show gal by pattern  which returns a Contact ID   
Contact: C.389c540e94a57a64

But this cannot be used to delete the contact.
gam select "targetDom" delete contact C.389c540e94a57a64

can I delete gal contacts by email address?

**Comment by taers232c** [comment]
Eric,

The current version is 6.10.02 not 6.08.03. It appears to me that you are managing domain shared contacts.
Do: gam select "targetDom" config verify
Is domain set? If not, do: gam select "targetDom" config domain "targetDom".com.au save

Do: gam select "targetDON" show contact emailmatchpattern axxx.hxxx@yyyy.com
This should give you a Contact ID that can be deleted.

I'm in California (PST) and am generally available starting at 8:00AM PST. I can be available Sunday evening (your Monday morning) to have a Google Meet/Zoom or on any other evening.

Ross

**Comment by ericwhiteau** [comment]
Hello Ross, 
We can look at it during the week.  no stress.

Yes gam select dom1 config verify   shows dom1 config and secret...
gam select dom2 config verify shows dom2 config and secret.

and the correct sets of active users and gal contacts is being returned from the two different domains.

I will test with 6.10  just to see if that is different.

have a good weekend.

**Comment by ericwhiteau** [comment]
and if it wasn't clear.  this has been running weekly for 8 months successfully with V5. with the same config.

**Comment by taers232c** [comment]
Eric,

Do the two gam salect domx config verify show domain = xxx or domain =

Beause of changes in the Google APIs, this value must be set.

Ross
--
***@***.***

**Comment by ericwhiteau** [comment]
update.
I have done a fresh install of 6.10  and added the domain references to the configs.

We now have correct behaviour.  on the add and remove of GAL contacts.
thank you.

Note.   gam select dom   show contact emailmatchpattern  aa@bb.com  now provides meaningful contact ID as well.

Domain: xxx.com.au, Show maximum of 5412 Contacts
  Contact: 3a6cae7d8ecd55a9 (2443/5412)
    Updated: 2021-11-30T13:01:14Z

3a6cae7d8ecd55a9  can be used to delete.   

thanks again.
