### ISSUE TITLE
Count mimetype created pr. day i a folder (incl subfolders) 

### ISSUE THREAD

**Issue by sorentorp** [taers232c/GAMADV-XTD3#220]
Hi
I want to create som usage statistics of our assignment turn-in system.

Currently I pull all documents from a folder like this

> gam csv /home/xxxxxx/gam/config/td.csv gam config csv_output_row_filter "'^mimeType$:regex:application/vnd.google-apps.document|application/vnd.google-apps.spreadsheet|application/vnd.google-apps.presentation'" user userxxx@aaks.dk print filelist select id ~folderid fields id,createdTime,mimeType,parents todrive

But this results in a sheet with 130000 rows and counting...

`gam user userxxxx@aaks.dk print filelist select id:0AGQOYxxxxxNzUk9PVA countsonly`

Gives me the type of data I like - one row. 

Is it possbile to do "countsonly" - created pr day?

**Comment by taers232c** [comment]
Try this:
gam config csv_output_row_filter "'^mimeType$:regex:application/vnd.google-apps.document|application/vnd.google-apps.spreadsheet|application/vnd.google-apps.presentation','createdTime:date=YYYY-MM-DD'" csv /home/xxxxxx/gam/config/td.csv gam user ***@***.*** ***@***.***> print filelist select id ~folderid fields id,createdTime,mimeType,parents todrive
You can replace YYYY-MM-DD with today or -1d for yesterday.

Ross
--
***@***.***

**Comment by sorentorp** [comment]
Hi Ross
Unfortunately this doesn't give me the days count - this gives me all the files and their filetype.
I was thinking something like:

Dato	Docs	Sheets	Sheets
2021-12-12	171	10	1
2021-12-11	49	5	0
2021-12-10	2846	58	129
2021-12-09	1189	13	51
2021-12-08	1500	48	57
2021-12-07	1581	41	35
2021-12-06	2595	89	55
2021-12-05	90	2	1
2021-12-04	32	3	3
2021-12-03	1259	15	6
2021-12-02	1193	28	15

**Comment by taers232c** [comment]
There is no way GAM can do this directly; a script will have to be written to process the GAM data into the format you want.

Ross

**Comment by taers232c** [comment]
See: https://github.com/taers232c/GAM-Scripts3/blob/master/GetDailyMimeTypeCreations.py
--
***@***.***

**Comment by sorentorp** [comment]
Wow! That is fast delivery! I'll get a workflow put together, and make great use of this! Thank you!

**Comment by taers232c** [comment]
See https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Drive-Files-Manage#create-files
