### ISSUE TITLE
Getting a simple list of all calendars including a flag for public

### ISSUE THREAD

**Issue by poseyjmac** [taers232c/GAMADV-XTD3#224]
I read this:

https://groups.google.com/g/google-apps-manager/c/S4KTFvcQBRs?pli=1

And this query works, but it takes a long time and gives me a HUGE amount of data I don't need. For instance for one calendar it has 30 rows to show me different users' access levels when I just want one row.(Ultimately, I just want to know if it's public or not, so I can generate a report) Is there a query I can do that only gives me one row per calendar? I'm using the latest version. 

Edit: 'print calsettings' would be useful, because it gives me just the one row except it doesn't give me a header for public/private

**Comment by taers232c** [comment]
gam config csv_output_row_filter "scope.type:regex:default" ...
--
***@***.***

**Comment by poseyjmac** [comment]
Thanks, that's great
