### ISSUE TITLE
Wrong timezone while creating or updating calendars' events

### ISSUE THREAD

**Issue by vargiuscuola** [taers232c/GAMADV-XTD3#227]
Hi,
the timezones of calendars' events created or modified by GAMADV-XTD3 are wrong.

I update a calendar event:

```bash
USER=<user>
$ gamadv-xtd3 calendar $USER update event id <id-event> timezone Europe/Rome start 2021-12-21T16:00:00+01:00 end 2021-12-21T19:00:00+01:00
Calendar: $USER, Update 1 Event
  Calendar: $USER, Event: <id-event>, Updated
```
Then I retrieve the event with:

```sh
$ gamadv-xtd3 calendar $USER print events matchfield summary '^<title>' matchfield status confirmed after '2021-12-20T00:00:00.000+01:00:00' fields start,end
Getting Events for <user>
calendarId,id,end.dateTime,end.timeZone,start.dateTime,start.timeZone,status,summary
<user>,<event-id>,2021-12-21T19:00:00Z,UTC,2021-12-21T16:00:00Z,UTC,confirmed,<title>
```

Note that the start and end time is wrong because the timezone gets modified to UTC.
I also checked the timezone set for the calendar and it's correctly set to `Europe/Rome`:

```sh
$ gamadv-xtd3 calendar $USER show settings
Calendar: $USER
  Summary: $USER
  Description:
  Location:
  Timezone: Europe/Rome
  ConferenceProperties:
    AllowedConferenceSolutionTypes: hangoutsMeet
```

**Comment by taers232c** [comment]
Varglu,

Do: gam config verify
What is the value of timezone?
Is this your timezone?

GAM converts all times presented by Google to he timezone specified by timezone.
Do: gam config timezone Europe/Rome save

Ross
--
***@***.***

**Comment by vargiuscuola** [comment]
Ok, I thought it depended by a workspace user/domain configuration, not a gam one.

```sh
$ gam config verify | grep timezone
  timezone = utc
  todrive_timezone = ''
$ gam config timezone Europe/Rome save
Config File: /root/.gam/gam.cfg, Saved

ERROR: Config File: /root/.gam/gam.cfg, Section: professionalevillaputzu.it, Item: timezone, Value: europe/rome, Expected: Z|(+|-(hh:mm))
$ gam config timezone +01:00 save
Config File: /root/.gam/gam.cfg, Saved
```

Now:

```sh
$ gam calendar $USER update event id $EVENT_ID timezone Europe/Rome start 2021-12-21T16:00:00+01:00 end 2021-12-21T19:00:00+01:00
$ gam calendar $USER print events matchfield summary '^summary' matchfield status confirmed after '2021-12-20T00:00:00.000+01:00' fields start,end
Getting Events for <user>@<domain>
calendarId,id,end.dateTime,end.timeZone,start.dateTime,start.timeZone,status,summary
<user>,<event-id>,2021-12-21T19:00:00+01:00,UTC,2021-12-21T16:00:00+01:00,UTC,confirmed,summary
```

Time is correct. Still don't know why it shows UTC in `start.timeZone` and `end.timeZone`, but that's not important as long as the time shows the correct timezone.

Thank you
Stefano

**Comment by taers232c** [comment]
Google maintains all times in UTC. The start.timeZone and end.timeZone fields tell you how to interpret the start.dateTime and end.dateTime fields.

Setting timezone = +01:00 tells GAM to convert all times from UTC  to the specified timezone. You still need to use start.timeZone and end.timeZone to figure when the meeting is if you set timezone to a value other that your local timezone.

**Comment by vargiuscuola** [comment]
I'm confused about how it works: if start.timeZone and end.timeZone are essential to figure out when the meeting is, how can I set them correctly?
I use `timezone Europe/Rome` in the `update event` command but that doesn't help: it's always get set to UTC.
The `start.timeZone` and `end.timeZone` maybe depends on a timezone setting for the single user (which I don't see anywhere in GSuite/Workspace)? I can only set the default timezone for all the organization, and it's set to Europe/Rome.

Anyway, a calendar event which shows `2021-12-21T19:00:00+01:00,UTC` as starting time in gam output, is correctly showed as starting at 19:00 in the calendar app, which is set to Europe/Rome timezone (as showed by `calendar <calendar-id> show settings` command).
