### ISSUE TITLE
Progress indicator doesn't clean previous line content

### ISSUE THREAD

**Issue by hroudny** [taers232c/GAMADV-XTD3#23]
In Advanced GAM, progress indicator is diplayed in the same line, changing as more users are downloaded. However, since email addresses have different lengths, after several updates, the status line shows relicts from previous updates like this:

gam print users
Getting all Users, may take some time on a large G Suite Account...
Got 6500 Users: paul@example.com - sue@example.com**mple.com**

To fix: it's necessary to print a special terminal control sequence "clear to end of line" after each progress update. This sequence is defined by `tput el`.

**Comment by taers232c** [comment]
Fixed 4.94.10
