### ISSUE TITLE
Feature Suggestion: add field/s for gam report <ActivityApplicationName>

### ISSUE THREAD

**Issue by vazome** [taers232c/GAMADV-XTD3#231]
Right now there is no way to select fields to output from [gam report ActivityApplicationName](https://github.com/taers232c/GAMADV-XTD3/wiki/Reports#activity-reports) with GAM itself

**Comment by taers232c** [comment]
The field names vary by event, there is no practical way to pre-specifiy the fields. If you are running the same report repeatedly, you can use output filtering: https://github.com/taers232c/GAMADV-XTD3/wiki/CSV-Output-Filtering

**Comment by vazome** [comment]
Works great
This is helpful thanks!
