### ISSUE TITLE
Ability to modify descriptionHeading

### ISSUE THREAD

**Issue by RonaldCarter89** [taers232c/GAMADV-XTD3#235]
Is it possible to add the ability to change the course descriptionHeading the same way we can change the course description

I know descriptionHeading is listed as an courseattirbue while description is listed as a courseattribute and coursefieldname

see https://github.com/taers232c/GAMADV-XTD3/blob/588006c4cbd43aa2c9c47597133cca3e0534dcf0/src/GamCommands.txt 2054 - 2086

**Comment by taers232c** [comment]
<CourseAttribute> heading is the descriptionHeading; In 6.15.03 heading and descriptionheading will be synonyms in <CourseAttribute> and <CourseFieldMa,e>.
