### ISSUE TITLE
Issue when using Cloud Identity API over Groups

### ISSUE THREAD

**Issue by dav1303** [taers232c/GAMADV-XTD3#236]
Hi Ross

I get a strange issue since 3 weeks now regarding an export which works fine before

When I use this command :

gam print cigroup-members fields name,type,role,memberkey,useremail > C:\0-IN\Groups\gcp_members.csv

I get this after 15 000 groups and it blocks every time with this error

Getting all Members, Managers, Owners for groups/03bj1y38367euls (15130/41564)
Getting all Members, Managers, Owners for groups/00tyjcwt3yha3yr (15131/41564)
Getting all Members, Managers, Owners for groups/026in1rg3ho0n1r (15132/41564)
Getting all Members, Managers, Owners for groups/045jfvxd0jkk3xf (15133/41564)
Getting all Members, Managers, Owners for groups/026in1rg0i7dvxo (15134/41564)
Getting all Members, Managers, Owners for groups/01x0gk3749b7ol2 (15135/41564)
Temporary error: serviceNotAvailable - The service is currently unavailable., Backing off: 16 seconds, Retry: 4/10
Temporary error: serviceNotAvailable - The service is currently unavailable., Backing off: 32 seconds, Retry: 5/10
Temporary error: serviceNotAvailable - The service is currently unavailable., Backing off: 60 seconds, Retry: 6/10
Temporary error: serviceNotAvailable - The service is currently unavailable., Backing off: 60 seconds, Retry: 7/10
Temporary error: serviceNotAvailable - The service is currently unavailable., Backing off: 60 seconds, Retry: 8/10
Temporary error: serviceNotAvailable - The service is currently unavailable., Backing off: 60 seconds, Retry: 9/10

ERROR: 503: serviceNotAvailable - The service is currently unavailable.

Thanks

**Comment by josjonkers** [comment]
Have an error too when creating dynamic groups using:
gam create cigroup email@domain.com name "Group Name" dynamic "user.suspended == false"

Temporary error: internalError - Internal error encountered., Backing off: 16 seconds, Retry: 4/10
Temporary error: internalError - Internal error encountered., Backing off: 32 seconds, Retry: 5/10
Temporary error: internalError - Internal error encountered., Backing off: 60 seconds, Retry: 6/10
Temporary error: internalError - Internal error encountered., Backing off: 60 seconds, Retry: 7/10

Thanks.

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation.

Ross
--
***@***.***

**Comment by taers232c** [comment]
Internal error caused by trying to create the 101st dynamic group, there is a limit of 100.
