### ISSUE TITLE
Chromebook KeyError: 'wanIpAddress'

### ISSUE THREAD

**Issue by carbm1** [taers232c/GAMADV-XTD3#237]
I am seeing this error while trying to pull Chromebook data.

& gam print cros fields deviceid,serialnumber,model,assetid,autoupdateexpiration,status,lastsync,lastenrollmenttime,orgunitpath,osversion,location,lastKnownNetwork,macAddress recentusers listlimit 1 orderby lastsync
Getting all CrOS Devices, may take some time on a large Google Workspace Account...
Got 4000 CrOS Devices...Traceback (most recent call last):
  File "__init__.py", line 59090, in ProcessGAMCommand
  File "__init__.py", line 19905, in doPrintCrOSDevices
  File "__init__.py", line 19725, in _printCrOS
KeyError: 'wanIpAddress'

I attempted running:
& gam config debug_level 1 print cros fields deviceid,serialnumber,lastKnownNetwork,macAddress orderby lastsync

Unfortunately this didn't yield any useful data as far as I could tell and it failed at the same place.

**Comment by carbm1** [comment]
I realized I wasn't running the latest version. Upgraded to 6.15.06. Same error. Different line numbers.

Got 4000 CrOS Devices...Traceback (most recent call last):
  File "__init__.py", line 59962, in ProcessGAMCommand
  File "__init__.py", line 20091, in doPrintCrOSDevices
  File "__init__.py", line 19911, in _printCrOS
KeyError: 'wanIpAddress'

**Comment by taers232c** [comment]
Craig,

Send me Meet/Zoom invitation.

Ross
--
***@***.***

**Comment by carbm1** [comment]
6.15.07 fixed the issue! Thank you!
