### ISSUE TITLE
bad CPU type in executable

### ISSUE THREAD

**Issue by scv-m** [taers232c/GAMADV-XTD3#243]
MacBook Pro
Apple M1 Pro
macOS Monterey 12.2.1

Fresh install of GAMADV-XTD3 using
`bash <(curl -s -S -L https://git.io/fhZWP) -l
`

then any time the gam command is used, it throws a "bad CPU" error

`➜  ~ gam
zsh: bad CPU type in executable: /Users/sam/bin/gamadv-xtd3/gam`

Is this M1 Mac incompatibility or just your typical user error? 🤐

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation.

Rss
--
***@***.***

**Comment by scv-m** [comment]
Invited you via your email

**Comment by scv-m** [comment]
Fixed by running iTerm with Rosetta
