### ISSUE TITLE
Quota Exceeded and Write Request limited

### ISSUE THREAD

**Issue by duderin0** [taers232c/GAMADV-XTD3#246]
Hi there, I'm trying to mass-deprovision devices (mostly all my work with gam is device-based) and running into this message when running 
`gam csv retired-assets.csv gam update cros ~deviceId action deprovision_retiring_device acknowledge_device_touch_requirement`

`Temporary error: quotaExceeded - Quota exceeded for quota metric 'Write requests for Chrome Devices' and limit 'Write requests for Chrome Devices per minute per user' of service 'admin.googleapis.com' for consumer 'project_number:[REDACTED]'., Backing off: 16 seconds, Retry: 4/10`

We are on the free Education tier and for us, both of those are limited to 60 per minute per user. I tried changing api_calls_rate_check to True, and api_calls_rate_limit = 60, but around my 82nd device I'm still getting that message from above (though appended with 1/0:00:02 rather than the Backing off... message). I'm not able to increase the limits as it required adding a billing account, which I cannot do. 

Am I missing something, or what should I do? I apologize if this isn't the right place to post this support question.

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation.

ross.scroggs @ gmail.com

**Comment by duderin0** [comment]
Posting for posterity:
Was recommended to rerun commands through these methods instead, for 1) true multithreaded, 2) serial but done better, and 3) multithreaded of a different command, respectively:

gam redirect stdout deprovLog.txt multiprocess redirect stderr stdout csv RetiredAssetsList.csv gam update cros ~deviceId action deprovision_retiring_device acknowledge_device_touch_requirement

gam redirect stdout deprovLog.txt redirect stderr stdout croscsvfile RetiredAssetsList.csv:deviceId update action deprovision_retiring_device acknowledge_device_touch_requirement

gam redirect stdout updateOuLog.txt multiprocess redirect stderr stdout csv FixOU-List.csv gam update cros ~deviceId ou ~orgUnitPath

I apologize if my verbiage isn't quite correct.
