### ISSUE TITLE
formatjson dropping userEmail field?

### ISSUE THREAD

**Issue by scv-m** [taers232c/GAMADV-XTD3#248]
```
PS > gam show classroominvitations course 91554867539 role student
Course: money bags benny (91554867539), Show 1 Classroom Student Invitation
  id: OTE1NTQ4Njc1Mzl8MTA3NjA5NDMxMjAwMTU2OTU1MzY3
    role: STUDENT
    userid: 107609431200156955367
    userEmail: student.samn@mckinnonsc.vic.edu.au

PS > gam show classroominvitations course 91554867539 role student formatjson
[{"courseId": "91554867539", "id": "OTE1NTQ4Njc1Mzl8MTA3NjA5NDMxMjAwMTU2OTU1MzY3", "role": "STUDENT", "userId": "107609431200156955367"}]
```

First command contains userEmail, when appending formatjson - it is dropped.

**Comment by taers232c** [comment]
userEmail isn't dropped, formatjson is just showing the data returned by the API which only includes the courseId and userId

I could add the userEmail and courseName to the JSON data

**Comment by scv-m** [comment]
Does that mean that without formatjson it's actually performing multiple api calls? One for the invitations then one for each userid to pull their email?

**Comment by taers232c** [comment]
Sam,

Yes. Send me a Meet/Zoom invitation

Ross

ross.scroggs @ gmail.com
--
***@***.***

**Comment by scv-m** [comment]
Will do tomorrow morning! About to head off for the day, but keen have a look at the quickmove cros device issue I posted earlier too.

**Comment by taers232c** [comment]
I'm in California (PST) and can be available from 7-8 and then 9-1

**Comment by taers232c** [comment]
If you do print classroominvitations you'll get a CSV file that will be easier to process with a script if that's where you're headed.
