### ISSUE TITLE
Get all gmail delegations of an user?

### ISSUE THREAD

**Issue by lucamanga** [taers232c/GAMADV-XTD3#249]
Hello, if I print my delegations, I have a list of 0 elements (with show or print delegates). I think there's some problem

**Comment by taers232c** [comment]
Go to Gmail/Settings/Accounts and Import/Grant access to your account
What do you see?

**Comment by lucamanga** [comment]
"Mine" is only an example.
If i do (mymail@mail.com is my email address)

gam user mymail@mail.com print delegations

it doesn't show my delegations
is it right? Or I should use the GAMScripts3 "ShowDelegations.py" script?

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation.

show delegations displays uses to whom you have delegsted your mailbox.

https://github.com/taers232c/GAM-Scripts3/blob/master/ShowDelegators.py <https://github.com/taers232c/GAM-Scripts3/blob/master/ShowDelegators.py>
This script shows users who have delegated their mailbox to you.

Ross
--
***@***.***

**Comment by NoSubstitute** [comment]
Minor typo in explanation.

`gam user user@mail show delegate` lists who you have delegated your mailbox to.
[ShowDelegators script](https://github.com/taers232c/GAM-Scripts3/blob/master/ShowDelegators.py) lists who have delegated their mailbox to you.

**Comment by lucamanga** [comment]
> show delegations displays uses to whom you have delegsted your mailbox. https://github.com/taers232c/GAM-Scripts3/blob/master/ShowDelegators.py <https://github.com/taers232c/GAM-Scripts3/blob/master/ShowDelegators.py> This script shows users who have delegated their mailbox to you.

Thank you, this script solved my issue.
