### ISSUE TITLE
Updating Wiki Page "ChromeOS Devices"

### ISSUE THREAD

**Issue by WardsParadox** [taers232c/GAMADV-XTD3#25]
I didn't just want to update the wiki page without letting folks know. I was struggling to find the items you can use in the `query` flag for ChromeOS devices. Google's latest page change seems to have removed the field definitions, so using wayback machine I was able to grab them.
As I was adding them, my markdown linter was going crazy and also allowed me to clean somethings up on the wiki page. I wanted to share it before adding and seeing if everyone was ok with the edit proposed. See gist here for the page.

https://gist.github.com/WardsParadox/b7ab1362f7a6f7ae2024b5de09feb8cc

**Comment by taers232c** [comment]
Looks very nice, call me on Google Hangouts so I can better understand some issues.

Ross

ross.scroggs@gmail.com

**Comment by taers232c** [comment]
The more I look, the better it gets. What's with the red <> and *

**Comment by WardsParadox** [comment]
I'll have to give you a call tomorrow sometime, got a load of meetings this evening.
The red `<>` and `*` are github's code renderer for shell scripts (I chose shell because PowerShell made the rest of the formatting very weird, at least in my render-er locally).

**Comment by WardsParadox** [comment]
So you could do:
` ```shell`
```shell
testingCMD --flag <DATA>
```
or
` ```plaintext`
```plaintext
testingCMD --flag <DATA>
```

**Comment by taers232c** [comment]
Thanks, talk to you tomorrow
