### ISSUE TITLE
GAMADV-XTD3 Installation Issue

### ISSUE THREAD

**Issue by perickson920** [taers232c/GAMADV-XTD3#260]
I have followed the instructions at 
https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM#windows

All seems to go well until the end where I need to Verify GAMADV-XTD3 service account access.

All 26 scopes show Fail even hours after finishing the installation. I have tried it 2 different times on 2 computers with the same result.

C:\GAMADV-XTD3>gam user user@domain.com check serviceaccount
System time status
  Your system time differs from admin.googleapis.com by 5 seconds           PASS
Service Account Private Key Authentication
  Authentication                                                            PASS
Service Account Private Key age; Google recommends rotating keys on a routine basis
  Service Account Private Key age: 424 days                                 WARN
Domain-Wide Delegation authentication:, User: user@domain.com, Scopes: 26
  https://mail.google.com/                                                  FAIL (1/26)
  https://sites.google.com/feeds                                            FAIL (2/26)
  https://www.google.com/m8/feeds                                           FAIL (3/26)
  https://www.googleapis.com/auth/apps.alerts                               FAIL (4/26)
  https://www.googleapis.com/auth/calendar                                  FAIL (5/26)
  https://www.googleapis.com/auth/classroom.announcements                   FAIL (6/26)
  https://www.googleapis.com/auth/classroom.coursework.students             FAIL (7/26)
  https://www.googleapis.com/auth/classroom.courseworkmaterials             FAIL (8/26)
  https://www.googleapis.com/auth/classroom.profile.emails                  FAIL (9/26)
  https://www.googleapis.com/auth/classroom.rosters                         FAIL (10/26)
  https://www.googleapis.com/auth/classroom.topics                          FAIL (11/26)
  https://www.googleapis.com/auth/cloud-identity                            FAIL (12/26)
  https://www.googleapis.com/auth/cloud-platform                            FAIL (13/26)
  https://www.googleapis.com/auth/contacts                                  FAIL (14/26)
  https://www.googleapis.com/auth/contacts.other.readonly                   FAIL (15/26)
  https://www.googleapis.com/auth/datastudio                                FAIL (16/26)
  https://www.googleapis.com/auth/directory.readonly                        FAIL (17/26)
  https://www.googleapis.com/auth/documents                                 FAIL (18/26)
  https://www.googleapis.com/auth/drive                                     FAIL (19/26)
  https://www.googleapis.com/auth/drive.activity                            FAIL (20/26)
  https://www.googleapis.com/auth/gmail.modify                              FAIL (21/26)
  https://www.googleapis.com/auth/gmail.settings.basic                      FAIL (22/26)
  https://www.googleapis.com/auth/gmail.settings.sharing                    FAIL (23/26)
  https://www.googleapis.com/auth/keep                                      FAIL (24/26)
  https://www.googleapis.com/auth/spreadsheets                              FAIL (25/26)
  https://www.googleapis.com/auth/userinfo.profile                          FAIL (26/26)
Some scopes FAILED!

**Comment by taers232c** [comment]
Are you substituting a valid domain email address for ***@***.*** ***@***.***>?

Send me a Meet/Zoom invitation.

Ross
--
***@***.***

**Comment by perickson920** [comment]
Yes, I am entering my Super User ***@***.*** address.

Invitation:

meet.google.com/mqn-xcwp-sad


---

*Paul Erickson *| IT Dept



Direct: 920-425-9802

Cell: 920-362-4880

Green Bay, WI

www.jonessign.com

Facebook <https://www.facebook.com/JonesSignCompany> | I
<https://www.instagram.com/jonessignco1910_/>nstagram
<https://www.instagram.com/jonessignco1910_/> |  LinkedIn
<https://www.linkedin.com/company/jones-sign-co--inc-/> |  Twitter
<https://twitter.com/jonessign>
