### ISSUE TITLE
"makesecuritygroup" not functioning for gam update cigroup (existing dynamic group)

### ISSUE THREAD

**Issue by itstom20** [taers232c/GAMADV-XTD3#261]
Hey all,

Command: gam update cigroup staff@domain.com makesecuritygroup

This command sends the following:
send: b'{"labels": {"cloudidentity.googleapis.com/groups.discussion_forum": "", "cloudidentity.googleapis.com/groups.security": ""}}'

Which gives:
reply: 'HTTP/1.1 400 Bad Request\r\n'

staff@domain.com is a dynamic group. I think that GAM is sending only discussion_forum and security, which is causing the API to spit back a 400 since the request didn't include dynamic in the mapping. It thinks you're trying to remove the dynamic label so doesn't let you add security label.

(context: dynamic cigroups already successfully created by GAM)

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation

Ross

**Comment by taers232c** [comment]
Tom, 6.20.04 is available. Thanks for the help, Ross

**Comment by itstom20** [comment]
Ross - initial testing is a success. You're the man!

I'll add it to the wiki.
