### ISSUE TITLE
Query properties leads to KeyError-Exception

### ISSUE THREAD

**Issue by jalmeroth** [taers232c/GAMADV-XTD3#27]
I tried to query the following, which perfectly works in API-Explorer, but leads to a KeyError-Exception in GAMADV-XTD3:
```
./gam user john.doe@acme.com show filelist fields id,properties query "properties has { key='CloudMigrator-Version' and value='3.15.5.0' }"
Getting all Drive Files/Folders that match query ('me' in owners and properties has { key='CloudMigrator-Version' and value='3.15.5.0' }) for john.doe@acme.com
Traceback (most recent call last):
  File "gam.py", line 41948, in ProcessGAMCommand
  File "gam.py", line 31631, in printFileList
  File "gam.py", line 3566, in _processGAPIpagesResult
KeyError: " key='CloudMigrator-Version' and value='3"
```

**Comment by taers232c** [comment]
Replace the {} with () and try.
> /gam user john.doe@acme.com show filelist fields id,properties query "properties has ( key='CloudMigrator-Version' and value='3.15.5.0' )"
Ross
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
() now work in 4.95.11

Test and report.

Thanks,

Ross

**Comment by jalmeroth** [comment]
Using `()` leads to an `Invalid` query, but `{}` seems to work now.
