### ISSUE TITLE
[Feature Request] Add formatjson to gam info resoldcustomer

### ISSUE THREAD

**Issue by jay-eleven** [taers232c/GAMADV-XTD3#270]
Hi Ross!

Almost all `gam` commands that `info`|`show`|`print` information allow converting to a JSON object using the `formatjson` argument.
However, it's not available for `gam info resoldcustomer <CustomerID>`.

Would it be possible to add it? 😅

**Comment by taers232c** [comment]
Will do.
--
***@***.***

**Comment by taers232c** [comment]
Done 6.21.07

**Comment by jay-eleven** [comment]
Tested, works like a charm.

Thanks for the fast turnaround Ross!!
