### ISSUE TITLE
Documentation - Add instructions to create symlink for macOS/Linux

### ISSUE THREAD

**Issue by Prodeguerriero** [taers232c/GAMADV-XTD3#277]
Hi @taers232c 

Following the conversation we had yesterday, I have been tinkering with my GAM setup. We have been having issues calling gam within bash scripts, as the alias is not available to the script unless we source it (or hard code the path into the script).

The solution I found is to create a symlink `/usr/local/bin/gam` that points to `~/bin/gamadv-xtd3/gam`. By doing so, the alias is not needed anymore, as `/usr/local/bin` is part of `$PATH`.

Would it be an idea to add instructions about creating this symlink [here](https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Install-Advanced-GAM#set-an-alias)?
Can you think of any reason to not use the symlink instead of an alias?

**Comment by taers232c** [comment]
Thanks, done.

**Comment by Prodeguerriero** [comment]
Great, thanks! Closing :)
