### ISSUE TITLE
ERROR: [Errno 13] Permission denied: '/Users/admin'

### ISSUE THREAD

**Issue by myossiv** [taers232c/GAMADV-XTD3#279]
i got this error when running this command in mac terminal
gam user jdoe add sendas groupname "name wanted to be shown"

**Comment by taers232c** [comment]
This is a local permissions issue; what does this command do: gam version

**Comment by myossiv** [comment]
3.0.3.1

**Comment by myossiv** [comment]
This is what i get


[image: image.png]





Yossi Vizel
***@***.***
0543305010
