### ISSUE TITLE
Error reading Google Response or writing to custInfo.json

### ISSUE THREAD

**Issue by chriolant** [taers232c/GAMADV-XTD3#28]
We tried using the `gam create resoldcustomer` command to create a new customer but it attempted to read/write to a seemingly undocumented custInfo.json file. Even if we pre-create the create the file in the same directory, it still causes an error:

> Traceback (most recent call last):
>   File "gam.py", line 42810, in ProcessGAMCommand
>   File "gam.py", line 8901, in doCreateResoldCustomer
>   File "json/__init__.py", line 357, in loads
>   File "json/decoder.py", line 337, in decode
>   File "json/decoder.py", line 355, in raw_decode
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

My guess is that it fails to read the response from the Google API and thus, throws an exception. We tested this on Ubuntu 18.04 LTS on Python 3.6.8

**Comment by taers232c** [comment]
Fixed 4.96.19
--
ross.scroggs@gmail.com

**Comment by chriolant** [comment]
Thanks! That was fast. Will download, test and revert.

**Comment by chriolant** [comment]
Oops. You closed it before I could revert. Issue solved! Thank you.
