### ISSUE TITLE
Suppressing output

### ISSUE THREAD

**Issue by scv-m** [taers232c/GAMADV-XTD3#291]
When I run `gam print course-participants course STUDENTS-2020 show teachers` I get `Got 5 Teachers for Course: 91554867539...` followed by the output.

How would I suppress the "Got 5 Teachers..." message?

**Comment by jay-eleven** [comment]
Hi scv-m!

Gam provides different ways to redirect its output.
I don't have access to a GAFE domain and can't test, but the `Got 5 teachers for course...` **might** be printed to stderr, so all you need to do is redirect stderr to null.

Please check https://github.com/taers232c/GAMADV-XTD3/wiki/Meta-Commands-and-File-Redirection

**Comment by taers232c** [comment]
See: https://github.com/taers232c/GAMADV-XTD3/wiki/gam.cfg#variables
`gam config show_gettings false save`

**Comment by taers232c** [comment]
Sam,

All of the Getting/Got messages can be suppressed.gam config show_getings false save

Ross
--
***@***.***
