### ISSUE TITLE
SendAs Signature File

### ISSUE THREAD

**Issue by CartoonHero79** [taers232c/GAMADV-XTD3#292]
Hello,
I'm having some trouble with updating the SendAs Signatures using a text file.  The syntax I'm attempting to use works fine with updating the email signature of the primary email address, but I'm getting an "Invalid argument" on the file name when I try to do the same for the sendas signature.  Here's the bit that's not working:

`gam user user@domain update sendas sendas@domain signature file path\filename.txt`

I did do a test without the file option and was to update the signature to a single word of quoted text.  That's what makes me feel like I'm close and that I'm just missing something basic.

There are no spaces in my path or filename but I've tried with/without quotes.  I've tried using a .html file with the additional html command after the file name.  I've also tried changing the directory to the folder where the file exists and eliminating the path from the command.  I did also try removing the file option and jamming in the whole text string that I use to write to the text file.  However, it's a fair bit of badly coded html and it errors with what looks like an issue with where some quotes are placed.  Since the same text in a file works for the main email signature, I'm assuming/hoping that it will work with the sendas signature as well.

_gam version
GAMADV-XTD3 4.94.10 - https://github.com/taers232c/GAMADV-XTD3
Ross Scroggs <ross.scroggs@gmail.com>
Python 3.7.4 64-bit final
google-api-python-client 1.7.8
httplib2 0.13.0
oauth2client 4.1.3
Windows 8.1 6.3.9600   AMD64_

Any help would be greatly appreciated.

Thank you

**Comment by taers232c** [comment]
Syntax not clear, I'll correct.
You want: gam user ***@***.*** update sendas ***@***.*** file path\filename.txt

Ross
--
***@***.***

**Comment by CartoonHero79** [comment]
Thank you so much!!
