### ISSUE TITLE
skipping multiparent folders on the move drivefile command

### ISSUE THREAD

**Issue by FluXs** [taers232c/GAMADV-XTD3#295]
Hi There, 

We are moving files from personal drives using the **move drivefile** command and have come across a slight issue, this particular tenant has not had its "multi-parent" drives changed to shortcuts (https://support.google.com/drive/answer/10864219) so we are coming across issues where the move command is crawling these 'multi-location / parent' folders (not owned by the user) and recreating the shortcuts and folders. 

Is there a way to skip these types of multiparent folders from the **gam <UserTypeEntity> move drivefile <DriveFileEntity>** command?

For reference, we are running the **claim ownership** command on the root of their personal drive to clean up permissions beforehand, but have been caught off-guard by these multi-location folders.

Thanks again

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation.

ross.scroggs @ gmail.com
