### ISSUE TITLE
Incorrect Error message

### ISSUE THREAD

**Issue by j91mcmurdo** [taers232c/GAMADV-XTD3#304]
Hey,

When you attempt to delete datastudiopermissions and use an account which doesn't have the correct permissions the error message says "Data Studio API not enabled"

![Untitled drawing](https://user-images.githubusercontent.com/66623491/190119516-74893c10-dbd7-406a-a128-2a598cb91006.png)

See attached screenshot

**Comment by taers232c** [comment]
Rerun the command for user ssmart like this
```
gam config debug_level 1 user ssmart ...
```

The last few lines of the debug output will show me the actual error returned from Google and I can adjust the error message.

Thanks

**Comment by taers232c** [comment]
Fixed 6.26.15

Thanks

**Comment by j91mcmurdo** [comment]
Cheers Ross :)
