### ISSUE TITLE
Issues with 6.26.16 and 6.26.17. Unable to update due to error code 137.

### ISSUE THREAD

**Issue by 4minh** [taers232c/GAMADV-XTD3#305]
Hi,
I'm having issues executing gam binaries for `6.26.16` and `6.26.17` on a macOS 12.6 machine. Luckily, `6.26.15` works without issues. On a linux host, `6.26.17` binaries work without issues.
```
gam --version
[1]    33844 killed     ~/bin/gamadv-xtd3/gam --version
```
Afterwards, the binaries are auto-deleted.

Running the update command `bash <(curl -s -S -L https://git.io/fhZWP) -l` results in this error:
```
Checking GitHub URL https://api.github.com/repos/taers232c/GAMADV-XTD3/releases for latest GAM release...

Getting file and download URL...

Downloading file gamadv-xtd3-6.26.17-macos-x86_64.tar from https://github.com/taers232c/GAMADV-XTD3/releases/download/v6.26.17/gamadv-xtd3-6.26.17-macos-x86_64.tar to /var/folders/96/pjgq_rpj0plg8rd_tqw4b1xm0000gn/T/tmp.TORdsS3G.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 17.8M  100 17.8M    0     0  11.6M      0  0:00:01  0:00:01 --:--:-- 20.2M
Extracting archive to /Users/mn/bin

Finished extracting GAM archive.

gam alias already exists in profile file /Users/mn/.bash_profile. Skipping add.

gam alias already exists in profile file /Users/mn/.zshrc. Skipping add.

Here's information about your GAM upgrade:

/dev/fd/11: line 270: 33608 Killed: 9               "$target_dir/$target_gam" version extended
ERROR: Failed running GAM for the first time with return code 137. Please report this error to GAM mailing list. Exiting.
```

A similar [issue](https://groups.google.com/g/google-apps-manager/c/nTomqYdrkn8) in Jay's older gam was due to an issue with the archive files. Could that be the case here, or is it isolated to my environment?

**Comment by taers232c** [comment]
Curious,

Can you send me a Meet/Zoom invitation?

Ross
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
If the binaries are auto-deleted, it sounds like an anti-virus issue or System Preferences/Security & Privacy/General

Ross
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
Do: alias

What is the alias for gam?

Ross
----
Ross Scroggs
***@***.***

**Comment by 4minh** [comment]
Hi Ross, apologies for the delay. I'm not aware of any changes to my machine, but I'm now able to upgrade to a newer version (6.27.05) without issues. FWIW, my alias was set to "~/bin/gamadv-xtd3/gam". Thank you for your quick response!
