### ISSUE TITLE
showownedby is not a valid argument

### ISSUE THREAD

**Issue by pchojnacki** [taers232c/GAMADV-XTD3#308]
Hi

I try to use command:
gam user <User Email Address> print filelist fullquery "not 'me' in owners and 'root' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false" showownedby others todrive

from Documentation (section Print File List -> Not-Owned Top Level Folders (Shared)):
https://sites.google.com/jis.edu.bn/gam-commands/services/drive?authuser=0#h.p_GhAvc_-iEDeW

but I get an error:
ERROR: showownedby is not a valid argument for "gam <users> show filelist"

I have installed a newest version of GAMADV-XTD3.

Thank you for help.

**Comment by taers232c** [comment]
Two things:
There is no user specified in the command:
gam user print filelist fullquery "not 'me' in owners and 'root' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false" showownedby others todrive
You want:
gam user ***@***.*** print filelist fullquery "not 'me' in owners and 'root' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false" showownedby others todrive

The error message is coming from Standard GAM, not advanced GAM.

What platform are you on?

Ross
----
Ross Scroggs
***@***.***

**Comment by pchojnacki** [comment]
Of course I replaced <User Email Address> with e-mail address. :)
I'm sorry, it was my fault. I did fresh install but still with GAM not GAMADV and all the time I was sure that was GAMADV.
It works now.

Thank you for your reply and time.
