### ISSUE TITLE
Transferring file to parent / root folder

### ISSUE THREAD

**Issue by SurrounDTech** [taers232c/GAMADV-XTD3#317]
Hi,

I am trying to transfer a file from one user's sub folder to another user's root (my drive) and have been trying the following command, but I can't seem to get it to work with targetuserorphansfoldername "". If a folder name is added, the command works correctly but does not when using just the "". Am I running this incorrectly? 

`gam user user@domain.com transfer drive otheruser@domain.com select <FileID> targetuserfoldername "" retainrole writer nonowner_targetrole source`

I receive the following error and it looks to be ignoring the ""

![image](https://user-images.githubusercontent.com/65645186/203489429-aca1ae4c-5ea8-42c5-a6ae-d08ac67d56b7.png)

With the retainrole removed to just have ""

![image](https://user-images.githubusercontent.com/65645186/203489640-6206925d-181d-46fe-92fc-8f5cfaff994c.png)

Thanks in advance for your help.

**Comment by taers232c** [comment]
The fact that the quotes in the command line are blue and all other characters are white is interesting; they are clearly not being recognized by the command line parser.
You reference targetuserorphansfoldername "" but I don't see that in the command.

I'm in California (PST) and am available to Meet/Zoom.

Ross

----
Ross Scroggs
***@***.***

**Comment by SurrounDTech** [comment]
Hi Ross,

Thanks for the reply and my mistake I should have proofread what I had posted it was the targetuserfoldername "" which was working not the Orphan version (bad copy and paste). I was actually running this in a PowerShell window so will try in just plain cmd and let you know how I go.

**Comment by SurrounDTech** [comment]
Hey Ross, can confirm it was the powershell windows, sorry I should have picked up on this before logging a ticket.

**Comment by taers232c** [comment]
It should work in PowerShell, I'm still curious about the blue quotes.
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
We can do a Meet/Zoom if you'd like.
----
Ross Scroggs
***@***.***

**Comment by SurrounDTech** [comment]
Hey Ross,

Sorry I am in and out of meeting today (Australian based). The blue is just the colour anything in quotes in PowerShell Windows Terminal. 

Working in CMD via Windows Terminal
![image](https://user-images.githubusercontent.com/65645186/203667419-c17b1003-4a58-4f0b-9012-b40e4994392b.png)

Not working Powershell via Windows Terminal (Blue quotes)
![image](https://user-images.githubusercontent.com/65645186/203667547-3e564f12-ab90-4d16-9b42-ae6618ed5814.png)

Standard Powershell Window (grey quotes)
![image](https://user-images.githubusercontent.com/65645186/203667726-9802ebca-382f-4d85-9aab-9c3f9843bb23.png)

Get-ChildItem with Blue quotes
![image](https://user-images.githubusercontent.com/65645186/203668008-7842965c-5044-45c8-a0ed-3ba2684d710d.png)

Windows Terminal Version
![image](https://user-images.githubusercontent.com/65645186/203667768-35f9876e-a772-41af-97aa-8af268732448.png)

PowerShell Version
![image](https://user-images.githubusercontent.com/65645186/203667835-1afa9c84-9c8f-4dcb-abb9-5cfbd8e7cbf8.png)

**Comment by taers232c** [comment]
See: https://github.com/taers232c/GAMADV-XTD3/wiki/Command-Line-Parsing#windows-powershell <https://github.com/taers232c/GAMADV-XTD3/wiki/Command-Line-Parsing#windows-powershell>

To pass an empty argument you need `"`"

Ross
----
Ross Scroggs
***@***.***

**Comment by SurrounDTech** [comment]
Thanks Ross
