### ISSUE TITLE
[Question] Query email when using command data from Google Sheets

### ISSUE THREAD

**Issue by iKeqing** [taers232c/GAMADV-XTD3#320]
Hi Ross,

I tried using the gam command below to collect data from google sheets but it seems doesn't work, can you help to have a look at how to fix it? I believe is somewhere wrong with after:"~Date" & from:"~Email", how can I use : with ""?

gam csv gsheet it@xxx.com 1V6yO1Jy4mgnAwZ1o7S3a6W3l6aNRs0 "Sheet1" gam user "~Email" print messages query after:"~Date" and query from:"~Email" headers all showattachments todrive tduser it@xxx.com

Thanks in advance.

**Comment by taers232c** [comment]
You want:

When you embed a CSV column name in an argument, you surround it with ~~

I'm assuming that you want one todrive upload, so I corrected for that.
> gam redirect csv - multiprocess todrive tduser ***@***.*** ***@***.***> csv gsheet ***@***.*** ***@***.***> 1V6yO1Jy4mgnAwZ1o7S3a6W3l6aNRs0 "Sheet1" gam user "~Email" print messages query "after:~~Date~~ from:~~Email~~" headers all showattachments 
> 
Ross
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
See: https://github.com/taers232c/GAMADV-XTD3/wiki/Bulk-Processing#csv-files

Scroll down to just above the line Example

Ross
----
Ross Scroggs
***@***.***
