### ISSUE TITLE
Another profilephoto question

### ISSUE THREAD

**Issue by DanielMalmgren** [taers232c/GAMADV-XTD3#326]
Hi.
Is there any way getting the gam <UserTypeEntity> get profilephoto command to not save any file at all? I am using the returned base64 info from the command so I don't need the command to save anything at all. I thought it did that if I provided neither the drivedir nor targetfolder arguments but I just realized it saves the file anyway.

**Comment by taers232c** [comment]
6.31.01 - I added nofile option

**Comment by DanielMalmgren** [comment]
Completely perfect! You're awesome, thank you!
