### ISSUE TITLE
GAM migration project

### ISSUE THREAD

**Issue by CertifiedCIO-jchambers** [taers232c/GAMADV-XTD3#329]
I'm trying to migrate a large client from GSuite to 365, and I want to write the tools in a way that can be reused for similar projects in the future.  

Best way I can think of to audit the Workspace shared drives to do any prep that needs to be done before throwing it in Sharepoint is to use Powershell to drive GAMADV commands.  I've already exported the teamdrive list to a CSV, and began reading the CSV into the powershell script and trying to run GAM commands from there... But this is where I run into a problem.

If I run "C:\GAMADV-XTD3\GAM user [username] print filelist select teamdriveid [id] allfields  1>"c:\gamwork\drives\[drivename].csv" from GAM itself, it spits out the CSV no problem.  But when I use powershell to do run the exact same command, I'll get something like this: 
![image](https://user-images.githubusercontent.com/125493843/219110548-4f4440e5-89b0-4d99-af54-6b2c4f3bd359.png)
And the resulting CSV isn't in CSV format... the delimiting commas will be there, but it'll still end up all lumped together in the first cell.  

I know the PS is generating the GAM command correctly, because if I instead output the $PrintCommand variables to a batch file and run that separately, it executes without a hitch.  So why is Powershell trying to run the print command failing here?  It worked perfectly with the preceding command to add my user as an organizer on all the shared drives.

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation and I'll help

Ross

**Comment by taers232c** [comment]
gam redirect csv drives[drivename].csv user [username] print filelist select teamdriveid [id] allfields

**Comment by CertifiedCIO-jchambers** [comment]
Fantastic, this is working beautifully, thank you!

**Comment by jay-eleven** [comment]
Solved, closing...
