### ISSUE TITLE
Suggestion - GamCommandSummary.txt

### ISSUE THREAD

**Issue by jhgarrison** [taers232c/GAMADV-XTD3#334]
Add a second file, GamCommandSummary.txt, generated via 

```
grep '^gam ' ~/bin/gamadv-xtd3/GamCommands.txt|sort>GamCommandSummary.txt
```

This makes finding a specific command (or browsing what is possible) much easier.

**Comment by taers232c** [comment]
Will do
----
Ross Scroggs
***@***.***
