### ISSUE TITLE
SharedDrives: updating theme - Update Failed: Internal Error

### ISSUE THREAD

**Issue by mlclemen2** [taers232c/GAMADV-XTD3#335]
I am working on a Google Shared Drive project.  I am creating Shared Drives with a custom theme.  However, recently, the themes stopped being applied and I see the error "Internal Error".  I tried updating to the current version.

gam user [user] update teamdrive [shareddrive_id] customtheme [imagefile_id] 0.0 0.0 1.0 color #37474f
User: [user], Shared Drive ID: [shareddrive_id], Update Failed: Internal Error

**Comment by taers232c** [comment]
I'm getting the same error, Google changed something.

I'm in California (PST) and am generally available staring at 7:30AM

Send me a Meet/Zoom invitation

ross.scroggs @ gmail.com

**Comment by mlclemen2** [comment]
It looks like they fixed it today.  Themes are now being applied properly without error

**Comment by taers232c** [comment]
It now works for me as well.
----
Ross Scroggs
***@***.***
