### ISSUE TITLE
Temporary error: rateLimitExceeded - User-rate limit exceeded. 

### ISSUE THREAD

**Issue by eduder** [taers232c/GAMADV-XTD3#337]
Attempting to delete a phishing e-mail from all of our users, based on a query with the message ID.

I get through about 374 of our 560 users, and everything stops with this error:

`Temporary error: rateLimitExceeded - User-rate limit exceeded.  Retry after 2023-03-07T18:03:15.961Z, Backing off: 16 seconds, Retry: 4/10
Temporary error: rateLimitExceeded - User-rate limit exceeded.  Retry after 2023-03-07T18:18:23.688Z, Backing off: 32 seconds, Retry: 5/10
Temporary error: rateLimitExceeded - User-rate limit exceeded.  Retry after 2023-03-07T18:18:23.688Z, Backing off: 60 seconds, Retry: 6/10
Temporary error: rateLimitExceeded - User-rate limit exceeded.  Retry after 2023-03-07T18:18:23.688Z, Backing off: 60 seconds, Retry: 7/10
Temporary error: rateLimitExceeded - User-rate limit exceeded.  Retry after 2023-03-07T18:18:23.688Z, Backing off: 60 seconds, Retry: 8/10`

I've tested this with Windows 10 and on macOS Ventura with the same result. According to the Google Cloud Console, I shouldn't be anywhere near our user quota.

I have tried tweaking these settings in gam.cfg:
`api_calls_rate_check = true
api_calls_rate_limit = 200`

With false to true, and 100 to 200, but it does not seem to resolve the problem. Any ideas? Thank you.

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation.
