### ISSUE TITLE
Update Managed Signatures to allow use of Google Cloud Storage for HTML file hosting

### ISSUE THREAD

**Issue by chromestrong** [taers232c/GAMADV-XTD3#340]
Hi Team,

Please update Managed Signatures to accept a HTML url from Google Cloud Storage.  

`### gam <UserTypeEntity> vacation <Boolean> subject <String>
        [(message|htmlmessage <String>)|(file|htmlfile <FileName> [charset <CharSet>])|(gdoc|ghtml <UserGoogleDoc>)]
        (replace <Tag> <UserReplacement>)*
        [html [<Boolean>]] [contactsonly [<Boolean>]] [domainonly [<Boolean>]]
        [start|startdate <Date>|Started] [end|enddate <Date>|NotSpecified]`

It is understood that this could be stored in Google Drive, however all of our images and marketing assets are in Google Cloud Storage and need to remain there.  Please create an option to allow a html file from Google Cloud Storage

`example ### gcshtml <PublicGoogleCloudStorageURL>`

Thanks Team

**Comment by taers232c** [comment]
Eric,

I'm working on it.

Ross
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
See: https://github.com/taers232c/GAMADV-XTD3/wiki/GamUpdates
See: https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Gmail-Send-As-Signature-Vacation

**Comment by chromestrong** [comment]
Nice! Thanks!
