### ISSUE TITLE
Tag Replace needs to be expanded to all User Attributes

### ISSUE THREAD

**Issue by chromestrong** [taers232c/GAMADV-XTD3#341]
Hi Team,

Currently Tag Replacement works for all schema's and most user attribute fields.  Please expand the user attribute fields to include the remaining user fields and subfields:

- [ **relation** ] admin_assistant|assistant|brother|child|domestic_partner|dotted-line_manager|exec_assistant|father|friend|manager|mother| parent|partner|referred_by|relative|sister|spouse|<String> <String>

- [ **website** ] app_install_page|blog|ftp|home|home_page|other|profile|reservations|resume|work|<String> <URL> notprimary|primary

- [ **im** ] type home other|work|(custom <String>) protocol aim|gtalk|icq|jabber|msn|net_meeting|qq| skype|yahoo|(custom_protocol <String>) <String> notprimary|primary

- [ **externalid** ] (employeeid <String>)| (externalid account|customer|login_id|network|organization|<String> <String>)

- [ **posix** ]  username <String> uid <Integer> gid <Integer> [system|systemid <String>][home|homedirectory <String>] [shell <String>] [gecos <String>] [os|operatingSystemType linux|unspecified|windows] [primary <Boolean>] endposix)

- [ **sshkeys** ] key <String> [expires <Integer>] endssh

One example use case for this is if we wanted to include the website field value ( more than one organization living in the same Google tenant so multiple websites ) and relation field value ( executive assistants emails) in a managed signature.

Thanks Team

**Comment by taers232c** [comment]
Done. https://github.com/taers232c/GAMADV-XTD3/wiki/GamUpdates
----
Ross Scroggs
***@***.***

**Comment by chromestrong** [comment]
Awesome!
