### ISSUE TITLE
File selection entity shortcut 'onlyteamdrives' not as expected

### ISSUE THREAD

**Issue by bepearson** [taers232c/GAMADV-XTD3#346]
I'm trying to display files accessible by a user only in shared drives using command: 

gam user user1@test.com print filelist choose onlyshareddrives showownedby any

This appears to only list files in the shared drive if the user has permissions at root of shared drive.  If the user only has access to a subfolder in the shared drive, the files are not displayed.  GAMADV-XTD3 version is  6.51.07

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation

ross.scroggs @ gmail.com
