### ISSUE TITLE
gam print aliases queries does not support arrays variables

### ISSUE THREAD

**Issue by vazome** [taers232c/GAMADV-XTD3#347]
Example:
```
GamArray=("use1r@mail1.com" "user2@mail2.com" "user3@mail3.com")
gam print aliases queries $GamArray suppressnoaliasrows todrive
```

Output:
Command: /Users/d.vazome/bin/gamadv-xtd3/gam print aliases queries user1@mail1.com >>>user2@mail2.com<<< user3@mail3.com suppressnoaliasrows todrive

**Comment by taers232c** [comment]
Daniel,

The elements of the list should be separated bu commas.
> ***@***.******@***.******@***.***")
Ross
----
Ross Scroggs
***@***.***

**Comment by vazome** [comment]
It helped, thanks!
