### ISSUE TITLE
Please update "add sendas" and "update sendas" to both use [name <String>]

### ISSUE THREAD

**Issue by chromestrong** [taers232c/GAMADV-XTD3#352]
Hi Team,

Please update the add sendas command to follow the same standard as the update sendas command by using `[name <String>] `instead of just `<String>`.  

`gam <UserTypeEntity> [create|add] sendas <EmailAddress> **<String>**
        [<SendAsContent> (replace <Tag> <UserReplacement>)*]
        [html [<Boolean>]] [replyto <EmailAddress>] [default] [treatasalias <Boolean>]`

`gam <UserTypeEntity> update sendas <EmailAddress> **[name <String>]**
        [<SendAsContent> (replace <Tag> <UserReplacement>)*]
        [html [<Boolean>]] [replyto <EmailAddress>] [default] [treatasalias <Boolean>]`

Thanks Team

**Comment by taers232c** [comment]
I'll update to allow the following; name must be the next argument after <EmailAddress>
gam <UserTypeEntity> [create|add] sendas <EmailAddress> name <String>

Ross
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
This is available in 6.54.02
----
Ross Scroggs
***@***.***

**Comment by chromestrong** [comment]
Thank you!
