### ISSUE TITLE
After update 6.54.04 command "gam all users show signature" don't work

### ISSUE THREAD

**Issue by patxirb** [taers232c/GAMADV-XTD3#353]
A false problem. Sorry.  I don't see how to delete this message.

So I edit it to leave my thanks to Ross for his incredible work.

Thanks a lot.

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation.

**Comment by patxirb** [comment]
https://meet.google.com/sch-uyad-kkp

**Comment by jay-eleven** [comment]
Closing
