### ISSUE TITLE
Allow using external mail service to send notification emails (Gmail API has strict sending limits).

### ISSUE THREAD

**Issue by victorhooi** [taers232c/GAMADV-XTD3#36]
I'm currently trying to batch-create a large number of users (~3000).

The ability to send the welcome email in GAM-X is awesome.

However, it GAM-X uses the Gmail API directly, which has very strict sending limits - these are on top of the API limits, and cannot be changed:

https://support.google.com/a/answer/166852?hl=en

Is there any way to use an external SMTP server, or mail service, to send these notification emails?

It would be great if this could be configurable, as you could point it to a mail service (e.g. Sendgrid), that did not have such limits.

**Comment by taers232c** [comment]
Victor,

At the moment no; it can be added with some work.
GAM wiil need:
SMTP Server address
SMTP port number
User name
Password (where would this be securely saved?)
Whether to use SSL or TLS

Ross
--
ross.scroggs@gmail.com

**Comment by victorhooi** [comment]
It would be great if this could be added - all the other G Suite API limit can be increased, to a certain degree - but it seems the Gmail sending limits are quite strict.

I think the reason is that Gmail is targeted more at sending emails via the UI, not for bulk sending. It also doesn't have the same deliverability guarantees compared to a real transactional email service (Sendgrid, Mailgun, Amazon SES etc.).

Hmm, for the password - is that something that can leverage the existing OS-level keychain/secure stores? (Obviously this would be platform specific - and you could always fall back to storing in cleartext if that fails, with the appropriate warnings etc.).

And if the user declined to store in the secure store, or on-disk, then perhaps we can simply prompt at each run of GAM-X?

**Comment by taers232c** [comment]
I added this in 4.98.04, did you ever test it? Reopen the issue if there is more to do.
