### ISSUE TITLE
new install gets 400 error after authorizing scope 

### ISSUE THREAD

**Issue by Bhodgson0** [taers232c/GAMADV-XTD3#361]
Hi, 

I have gone through the installation process, and after I select that scopes to authorize I get that big text blob of a URL link. 
When I paste the link into Chrome I get my Google credential sign in prompt. Once I click my google account I get a "BAR REQUEST error 400" screen and I can not continue your script as i don't have  a verification code or a unable to connect URL. 

System:  Mac Mini M1 chip 
OS:         Ventura 13.3
Browser:  Version 113.0.5672.92 (Official Build) (arm64)

**Comment by taers232c** [comment]
What scopes did you select? Google chokes if you select all scopes.
Unselect 37, 43, 46, 48; these are not commonly used.

Send me a Meet/Zoom invitation if you need help.

Ross
----
Ross Scroggs
***@***.***

**Comment by Bhodgson0** [comment]
Thanks Ross, 
That solved that, however Im stuck again when directed to the google workspace domain-wide delegation / client ID stage. 
I follow your instructions to overwrite the existing client ID
It adds successfully
I wanted 10,20 30 minutes. and it still fails. 
How long does it usually take before the tests pass?
Any thoughts on whats going on here?

**Comment by taers232c** [comment]
Usually a few seconds, but I've seen it take 15 minutes.

Makre sure that the email address you've entered is valid.

Send me a Meet/Zoom ibvitation if you need help.

Ross
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
Any luck? If not, send a Meet/Zoom invitateion
----
Ross Scroggs
***@***.***
