### ISSUE TITLE
Chat Documentation Missing Parameters

### ISSUE THREAD

**Issue by chromestrong** [taers232c/GAMADV-XTD3#364]
The documentation for this command appears to be missing some parameters.

![image](https://github.com/taers232c/GAMADV-XTD3/assets/51937796/befed664-c3ba-4961-9b2a-4a70d5646922)

**Comment by taers232c** [comment]
What do you believe is missing?

**Comment by chromestrong** [comment]
After reviewing it for the second time, its just confusing since chatmemberlist is not a list of chatmembers, its a list of chatmembers and their spaces.

**Comment by taers232c** [comment]
<ChatMember> ::= spaces/<String>/members/<String>
<ChatMemberList> ::= "<ChatMember>(,<ChatMember>)*"

That's how the API identifies a member, you are a member of a space (or many spaces)

**Comment by taers232c** [comment]
What are you trying to achieve?

**Comment by chromestrong** [comment]
As part of offboarding we want to remove a user from all of their chat spaces (just spaces) and this command at first glance looks like you can provide just a user or list of users and it will remove them from all of their spaces.

**Comment by taers232c** [comment]
This will delete the user from the SPACEs to which it belongs.
```
gam redirect csv ./UserChatSpaces.csv user user@domain.com print chatspaces

gam config csv_input_row_drop_filter "spaceType:regex:DIRECT_MESSAGE" redirect stdout ./DeleteUserChatMemberships.txt multiprocess redirect stderr stdout csv ./UserChatSpaces.csv gam user "~User" delete chatmember "~name" user "~User"
```

You can't delete a DirectMessage chat of which you are a member and you can't delete yourself from a DirectMessage chat
