### ISSUE TITLE
Option "noactionifalias" for groups 

### ISSUE THREAD

**Issue by Av3nGeR0809** [taers232c/GAMADV-XTD3#366]
Hi,

Through GAM Public Chat group I asked this question and was advised by Jay Lee to submit this as a feature request.

I wasn't aware that GAMADV can delete users based on their alias if connected to an active user. I created a user with the primary email "test@domain.com" and added an alias "tt@domain.com" to this user.
I went to delete a user using the alias instead of the primary email address and it deleted the actual user that that alias was attached to: "gam delete user tt@domain.com"

Now, Jay explained to me this is an expected behavior thanks to Google APIs allowing this of course.
Kim Nilsson suggested using "noactionifalias" option at the end of the command, which works perfectly for users.
That got me thinking "What about groups?", and I tested it and established that the same thing happens for groups as well.
However, there is no option to sidestep this for groups, like there is for users with "noactionifalias" at the end of the command.

We have a few customers that are using GAMADV and we assist them with compiling the commands based on their needs, and some of them have poor or no offboarding processes in place, and recently one of them got a list of users to delete/offboard from the HR. The issue here was that some of the users were already deleted and their email addresses were now aliases for active users, some 300 of which were accidentally deleted as a result (they also didn't know about the "noactionifalias" option).

Some of them also have groups where they are deleting some of them and adding those deleted groups' email addresses as aliases, which got me thinking about this "noactionifalias" option, but, have established it doesn't work for groups, only for users, hence me asking if you can kindly add this option to GAMADV.

Thank you in advance for your time on this!

**Comment by taers232c** [comment]
noactionifalias was added to Advanced GAM 6.61.01
----
Ross Scroggs
***@***.***
