### ISSUE TITLE
GDrive transfer or claim ownership doesn't work on shortcuts

### ISSUE THREAD

**Issue by Celestica-Edward** [taers232c/GAMADV-XTD3#369]
Hi,

The commands described below don't seem to handle changing the ownership of Drive Shortcuts. Can this be added?
When running these commands, they just skip over the shortcuts in a folder. We have a use case where we want these shortcuts to have a new owner. The shortcuts are organized in a folder already so we'd normally use the commands to change ownership of all files within the folder. The destination of the shortcuts could be pointing to anywhere else, outside of the parent folder potentially.

https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Drive-Ownership#transfer-ownership-of-files-that-a-source-user-owns-to-a-target-user
https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Drive-Ownership#claim-ownership-of-files-that-other-users-own

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation and I'll help investigate.

Ross

ross.scroggs @ gmail.com

**Comment by taers232c** [comment]
Shortcuts are owned by the owner of the folder that contains them, not by the user that created them.

Thus, if you claim ownership of a folder you own, nothing happens to the shortcuts in the folder as they are already owned by you.

If you claim ownership of a folder you don't own, the the shortcut ownership will be changed to you.
