### ISSUE TITLE
problem to remove suspended users who have been suspended for 3 years

### ISSUE THREAD

**Issue by mberva** [taers232c/GAMADV-XTD3#370]
Hi,
when I run a script for remove suspended users I view a WARNING.
I'm running GAMADV-XTD3 6.63.11
Appreciate you guys!

My command is:
gam config csv_output_row_filter "accounts.is_suspended:boolean:true,accounts.disabled_time:date<-1250d" report user user all parameters accounts:is_suspended,accounts:disabled_reason

OUTPUT is:

2023-09-07T07:07:26.353+00:00,0/1,Using 1 process...
2023-09-07T07:07:26.354+00:00,0,Processing item 1/1
Getting Reports for all users

WARNING: End date greater than LastReportedDate.

WARNING: csv_output_row_filter column "^accounts.is_suspended$" does not match any output columns

WARNING: csv_output_row_filter column "^accounts.disabled_time$" does not match any output columns
2023-09-07T07:07:27.383+00:00,0/1,Processing complete

**Comment by materemias** [comment]
I have the same warning even if I do something as basic as
```gam report users                                                                                          
Getting Reports for all users

WARNING: End date greater than LastReportedDate.```
and the report ends here...

**Comment by taers232c** [comment]
This is now handled in 6.63.12

Ross
----
Ross Scroggs
***@***.***
