### ISSUE TITLE
Error Downloading GAMADV-XTD3 on my MAC

### ISSUE THREAD

**Issue by Banqx** [taers232c/GAMADV-XTD3#371]
Hello,

I'm getting the below error message when i try to download the GAM files for installation.

_

Checking GitHub URL https://api.github.com/repos/taers232c/GAMADV-XTD3/releases for latest GAM release (unauthenticated)...

Getting file and download URL...

ERROR: assets value not found in JSON value of:

{'message': "API rate limit exceeded for 212.91.244.2. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", 'documentation_url': 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'}

_

Kindly assist.
![GAM download error ,sg](https://github.com/taers232c/GAMADV-XTD3/assets/99056498/7f243f07-a82b-449c-bd6b-068128fa3e0b)

**Comment by Banqx** [comment]
> Hello,
> 
> I'm getting the below error message when i try to download the GAM files for installation.
> 
> _
> 
> Checking GitHub URL https://api.github.com/repos/taers232c/GAMADV-XTD3/releases for latest GAM release (unauthenticated)...
> 
> Getting file and download URL...
> 
> ERROR: assets value not found in JSON value of:
> 
> {'message': "API rate limit exceeded for 212.91.244.2. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", 'documentation_url': '[https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'}](https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'%7D)
> 
> _
> 
> Kindly assist. ![GAM download error ,sg](https://user-images.githubusercontent.com/99056498/266992961-7f243f07-a82b-449c-bd6b-068128fa3e0b.jpg)

The command i'm running is 

bash <(curl -s -S -L https://raw.githubusercontent.com/taers232c/GAMADV-XTD3/master/src/gam-install.sh)

**Comment by taers232c** [comment]
This is a network issue at your end; you can download the update manually from here:
https://github.com/taers232c/GAMADV-XTD3/releases/tag/v6.63.13
gamadv-xtd3-6.63.13-macos-x86_64.tar.xz
or
gamadv-xtd3-6.63.13-macos-arm64.tar.xz

Send me a Meet/Zoom invitation and I'll help.

**Comment by Banqx** [comment]
> This is a network issue at your end; you can download the update manually from here: https://github.com/taers232c/GAMADV-XTD3/releases/tag/v6.63.13 gamadv-xtd3-6.63.13-macos-x86_64.tar.xz or gamadv-xtd3-6.63.13-macos-arm64.tar.xz
> 
> Send me a Meet/Zoom invitation and I'll help.

ah! yes it was actually an issue with the network.. Thanks.
