### ISSUE TITLE
Getting error while trying to transfer ownership of folder

### ISSUE THREAD

**Issue by xeroxoid** [taers232c/GAMADV-XTD3#372]
Hi, excellent work, the project rocks!

I am trying to transfer ownership of a folder `FOO` (and its contents) from user `XXX` to user `YYY`

I follow the command chain highlighted here: https://sites.google.com/jis.edu.bn/gam-commands/services/drive#h.9yk8eaecf289

First command generates the CSV with the files list, all ok.
Now when I run the second command that should loop over the files list:
```
gam csv gsheet XXX LONG_DRIVE_FILE_ID GSHEET_ID gam user ~Owner add drivefileacl ~id user YYY role owner
```
I get the error:
`zsh: no such user or named directory: Owner`

Is it an issue or am I doing something wrong?

Extra info:
GAM version: 6.63.14
OS: MacOS
Shell: zsh

**Comment by xeroxoid** [comment]
Scratch that, I followed the [Wiki docs](https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Drive-Ownership) and used 

```
gam <UserTypeEntity> transfer ownership <DriveFileEntity> <UserItem>
```

And all seems to have worked well!

**Comment by xeroxoid** [comment]
Scratch that, I followed the [Wiki docs](https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Drive-Ownership) and used 

```
gam <UserTypeEntity> transfer ownership <DriveFileEntity> <UserItem>
```

And all seems to have worked well!

**Comment by taers232c** [comment]
Use quotes
gam csv gsheet XXX LONG_DRIVE_FILE_ID GSHEET_ID gam user "~Owner" add drivefileacl "~id" user YYY role owner

----
Ross Scroggs
***@***.***
