### ISSUE TITLE
Error creating Project on GCP

### ISSUE THREAD

**Issue by Banqx** [taers232c/GAMADV-XTD3#373]
Hello,

I have past the download stage and on the installation stage, I have tried severally the steps in this repository (https://github.com/taers232c/GAMADV-XTD3) but still encountered issues.. Pls assist...find attached the error messages encountered.

![screen shot 2023-09-14 at 11 24 54](https://github.com/taers232c/GAMADV-XTD3/assets/99056498/4bac8aa0-5ecc-46a1-82e8-8d8b15163eb9)
![screen shot 2023-09-14 at 11 25 05](https://github.com/taers232c/GAMADV-XTD3/assets/99056498/d752523f-2873-453a-a53d-a5656ab0537b)

**Comment by taers232c** [comment]
See: https://cloud.google.com/iam/docs/keys-upload <https://cloud.google.com/iam/docs/keys-upload>

To get the permissions that you need to upload service account keys, ask your administrator to grant you the Service Account Key Admin  <https://cloud.google.com/iam/docs/understanding-roles#iam.serviceAccountKeyAdmin>(roles/iam.serviceAccountKeyAdmin) IAM role on the project, or the service account whose keys you want to manage. For more information about granting roles, see Manage access <https://cloud.google.com/iam/docs/granting-changing-revoking-access>.      

Ross
----
Ross Scroggs
***@***.***

**Comment by Banqx** [comment]
Hello Ross,

I have been granted Service account key admin and now there's a new error message:


![screen shot 2023-09-18 at 17 53 24](https://github.com/taers232c/GAMADV-XTD3/assets/99056498/b564246d-55c4-409a-b9ff-00714faa3c84)
