### ISSUE TITLE
Vacation End Date in Unix Format in 6.63.18

### ISSUE THREAD

**Issue by EddyH7** [taers232c/GAMADV-XTD3#376]
When printing users Vacation message details the end date shows in Unix Format:
gam user cs4eh print vacation
User,enabled,contactsonly,domainonly,startdate,enddate,subject,html,message
cs4eh@sheffield.ac.uk,True,False,False,2023-09-23,**1695769200000**,Out Of Office,True,".......

Testing previous version back to 6.61.00 the issue still appears, but going back to 6.60.00 and the date appears in human readable format.
User,enabled,contactsonly,domainonly,startdate,enddate,subject,html,message
cs4eh@sheffield.ac.uk,True,False,False,2023-09-23,**2023-09-26**,Out Of Office,True,"........

**Comment by taers232c** [comment]
This is fixed in 6.63.19
----
Ross Scroggs
***@***.***

**Comment by EddyH7** [comment]
Many thanks Ross!, that's amazing!
