### ISSUE TITLE
Cannot get all signatures associated with user object, Please add an "all" option

### ISSUE THREAD

**Issue by chromestrong** [taers232c/GAMADV-XTD3#377]
`gam user john.smith@example.com print signature todrive`

When running the command above only one signature is returned for a given user object.  We have options to get the signatures for "Primary" and "Default", but we do not have an option to get "All" signatures for an account object.

This is needed so that we can either remove them, or update them to be correct so users stop using custom signatures.

Please assist

**Comment by taers232c** [comment]
The Gmail API only supports seeing what the GUI calls "My signature", it does not support other signatures.
----
Ross Scroggs
***@***.***

**Comment by chromestrong** [comment]
Hmm, Bettercloud is able to do it somehow.  It looks like it queries for all of the aliases and then queries all the signatures for those aliases.

**Comment by taers232c** [comment]
See : https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Gmail-Send-As-Signature-Vacation#display-sendas
----
Ross Scroggs
***@***.***
