### ISSUE TITLE
Constant "Temporary Error: Internal Error - Internal..." 

### ISSUE THREAD

**Issue by kieranfoxe** [taers232c/GAMADV-XTD3#379]
I'm attempting to use `gam redirect csv -todrive ou <ouName> show lookerstudioassets` 

and I've encountered:

"Temporary error: internalError - Internal error encountered., Backing off: 16 seconds, Retry: 4/10.." 
until..
ERROR: 500: internalError - Internal error encountered.

I've not been able to get through without error yet.. It's the first time I've ever encountered this before.

**Comment by kieranfoxe** [comment]
Using: 

- GAMADV-XTD3 6.64.14
- Python 3.12.0 64-bit
- MacOS Ventura 13.6

**Comment by taers232c** [comment]
Get 6.64.15

gam redirect csv - todrive ou <ouName> print lookerstudioassets

Report results.

Ross
----
Ross Scroggs
***@***.***

**Comment by kieranfoxe** [comment]
Success! 

I was able to loop through the entire OU and generate the report in a Google sheet, as expected, without issue.

Thank you for the swift action, Ross and team!
