### ISSUE TITLE
Non-listed SKUID 

### ISSUE THREAD

**Issue by stephengale801** [taers232c/GAMADV-XTD3#382]
Working with GAM to update the Renewal Action for "Google Workspace Additional Storage." The SKUID from `gam print resoldsubscriptions` is listed as `1010430001`.  When I attempt to update with the following command, the SKUID is not recognized.

```gam update resoldsubscription <customer_id> 1010430001 renewal cancel```

error:
```ERROR: Invalid choice (1010430001): Expected <1010010001|1010020020|1010020025|1010020026|1010020027|1010020028|1010020029|1010020030|1010020031`|1010050001|1010060001|1010060003|1010060005|1010310002|1010310003|1010310005|1010310006|1010310007|1010310008|1010310009|1010310010|1010330002|1010330003|1010330004|1010340001|1010340002|1010340003|1010340004|1010340005|1010340006|1010350001|1010360001|1010370001|1010380001|1010380002|1010380003|1010390001|1010400001|1010470001|Google-Apps|Google-Apps-For-Business|Google-Apps-For-Government|Google-Apps-For-Postini|Google-Apps-Lite|Google-Apps-Unlimited|Google-Chrome-Device-Management|Google-Drive-storage-16TB|Google-Drive-storage-1TB|Google-Drive-storage-200GB|Google-Drive-storage-20GB|Google-Drive-storage-2TB|Google-Drive-storage-400GB|Google-Drive-storage-4TB|Google-Drive-storage-50GB|Google-Drive-storage-8TB|Google-Vault|Google-Vault-Former-Employee>```

I thought that there was a configuration option to use "Non-listed SKUIDs" but have not been able to locate documentation on this anywhere.

Also noted in the error message that there is a tick (`) by SKUID 1010020031.  Not sure if this is a typo, but I imagine that it is.

Happy to meet up via Meet if you require any additional information.

**Comment by taers232c** [comment]
Tick is an error, will fix.

Send Meet/Zoom invitation to discuss 1010430001
----
Ross Scroggs
***@***.***

**Comment by stephengale801** [comment]
Thanks again.
https://meet.google.com/wxt-vdvp-eji
Stephen Gale - (801) 900-3921

**Comment by taers232c** [comment]
Fixed/updated 6.65.04
----
Ross Scroggs
***@***.***
