### ISSUE TITLE
[Improvement] Add additional error message clarification and optional parameter to Course.DirectAddUser function for External members  

### ISSUE THREAD

**Issue by stephengale801** [taers232c/GAMADV-XTD3#385]
Example:
Internal Domain: `example.com`
External Domain: `example.org`

Command:
```gam course 123456789 add teacher newteacher@example.org```
Result:
```Course: 123456789, Teacher:newteacher@example.org Add Failed: 403: permissionDenied - @CannotDirectAddUser Unable to directly add the user to the course. Please check that the user account exists and is within the course admin's domain.```

Recommend directing users to the "Classroom Invitations Wiki" page, as this is typically what they will want to do.  Failure to include this reference in the error can be interpreted as the functionality cannot be accomplished via API.

Additionally, add an options parameter (something like [external], [retry], or [invite] ) to catch the error and retry w/o the accept invitation portion OR as an alias function of the aforementioned Invitation function to prevent excessive API calls which would return errors for each call when used as a part of a CSV with external participants.

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation.

Ross
----
Ross Scroggs
***@***.***

**Comment by stephengale801** [comment]
Hey Ross,
https://meet.google.com/rnu-uycf-opm

Thanks again.
Stephen Gale - (801) 900-3921

**Comment by taers232c** [comment]
6.65.06

Improved error message when trying to add external students/teachers to a course.

gam courses 544906261666 add student ***@***.***
Course: 544906261666, Add 1 Student
  Course: 544906261666, Student: ***@***.***, Add Failed: 403: permissionDenied - @CannotDirectAddUser Unable to directly add the user to the course. Please check\
 that the user account exists and is within the course admin's domain. Add external user with: gam user ***@***.*** create classroominvitation courses 54490626166\
6 role Student


----
Ross Scroggs
***@***.***
