### ISSUE TITLE
No Client access allowed

### ISSUE THREAD

**Issue by cverrilli** [taers232c/GAMADV-XTD3#387]
when running a gam command gam info user mtwillis@philasd.org i get the message No Client Access allowed

**Comment by taers232c** [comment]
Do: gam oauth create

If that doesn't solve the proble, send me a Meet/Zoom invitation.

Ross
----
Ross Scroggs
***@***.***

**Comment by cverrilli** [comment]
Invite below
pvg-scsg-wff meet.google.com/pvg-scsg-wff

Thanks,

Carmen



------------------------------------------------------
Mr. Carmen J. Verrilli
Technical Coordinator - Office of Technology Services
The School District of Philadelphia
440 N. Broad Street Philadelphia, PA 19130
Suite 404
***@***.***

*Click **here*
<https://philasd.co1.qualtrics.com/jfe/form/SV_6SiweqqjqE7deT3?Source=EMAILIT&Office=Office%20of%20Information%20Technology%20and%20Data%20Management>*
<https://philasd.co1.qualtrics.com/jfe/form/SV_6SiweqqjqE7deT3?Source=EMAILIT&Office=Office%20of%20Information%20Technology%20and%20Data%20Management>to
*

*tell us how we are doing!*


Any Questions? Please call the I.T. Help Desk at 215-400-5555 or email
at ***@***.***
***@***.***>.*


Visit *philasd.org/technology <http://philasd.org/technology>* for more
information.


Visit *sishelp.philasd.org <http://sishelp.philasd.org/>* for SIS training
resources.
