### ISSUE TITLE
oauth create never completes

### ISSUE THREAD

**Issue by enccsorg** [taers232c/GAMADV-XTD3#388]
I tried to create the oauth token and the first time I tried it just hung up on the screen after I clicked Allow to the scopes. I tried a shift-refresh of the browser and it seemed to give  a next page however once I pasted the URL into GAM-ADVXTD3 it told me **(invalid_grant) Bad Request**. I tried again and then it gave me **Access blocked: Authorization Error** at the top, at the bottom, **Error 400: Invalid scope**

`Some requested scopes were invalid. {valid=[https://www.googleapis.com/auth/chrome.management.policy, https://www.googleapis.com/auth/admin.directory.userschema, https://www.googleapis.com/auth/apps.licensing, https://www.googleapis.com/auth/admin.datatransfer, https://www.googleapis.com/auth/admin.directory.user, https://www.googleapis.com/auth/admin.directory.orgunit, https://www.google.com/m8/feeds, https://www.googleapis.com/auth/directory.readonly, https://www.googleapis.com/auth/admin.chrome.printers, https://www.googleapis.com/auth/admin.directory.resource.calendar, https://www.googleapis.com/auth/apps.groups.settings, https://www.googleapis.com/auth/classroom.guardianlinks.students, https://www.googleapis.com/auth/classroom.topics, https://www.googleapis.com/auth/admin.reports.audit.readonly, https://www.googleapis.com/auth/chrome.management.appdetails.readonly, https://www.googleapis.com/auth/admin.directory.device.mobile, https://www.googleapis.com/auth/classroom.courseworkmaterials, https://www.googleapis.com/auth/classroom.courses, https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/classroom.profile.emails, https://www.googleapis.com/auth/cloud-identity.groups, https://www.googleapis.com/auth/cloud-identity.inboundsso, https://www.googleapis.com/auth/admin.directory.customer, https://www.googleapis.com/auth/cloud-identity.orgunits, https://www.googleapis.com/auth/admin.directory.group, https://www.googleapis.com/auth/apps.groups.migration, https://www.googleapis.com/auth/classroom.announcements, https://www.googleapis.com/auth/siteverification, https://www.googleapis.com/auth/ediscovery], invalid=[https://www.googleapis.com/auth], noncanonical=[https://www.google.com/m8/feeds(https://www.googleapis.com`

I tried again with eliminating all but the bare minimum (I thought) from the request. It took me to a Google page asking me to select my account, then to give GAM permissions. Then it has hung for over half an hour. I'm concerned if I just shift-refresh again it will short circuit and not give the authorization, and I'm also concerned that if I don't, it will remain hung forever.* Unsure how to proceed. Is there an alternate method (not automated) to create the token?

* It eventually returned an error unable to connect page and I tried pasting that URL prior to "%scope" into GAM and again got the **(invalid_grant) Bad Request.**

**Comment by taers232c** [comment]
I'm in California (PST), send me a Meet/Zoom invitation.
It's a little after 3:15PM, I'll be around for a few hours and then again in the moring after 7:30AM

Ross
----
Ross Scroggs
***@***.***

**Comment by enccsorg** [comment]
sent via email and also here:
GAM help (this is enccsorg)
Tuesday, November 21 · 3:45 – 4:15pm
Time zone: America/Los_Angeles
Google Meet joining info
Video call link: https://meet.google.com/fnj-iirm-uon
