### ISSUE TITLE
Google Licenses

### ISSUE THREAD

**Issue by Connor1304** [taers232c/GAMADV-XTD3#389]
Is there a way to view the licenses available in an account to use so I can cross reference with the accounts being used currently?

**Comment by das1** [comment]
Perhaps

*gam print licenses*


--
Dan Schwartz | LTS - Systems Engineering  | Lehigh University |
***@***.***

**Comment by Connor1304** [comment]
That shows the active accounts I wanted to see all accounts?

**Comment by Connor1304** [comment]
Ok thank you, On another note am I able set set a specific license upon user creation?

**Comment by taers232c** [comment]
Yes. See: https://github.com/taers232c/GAMADV-XTD3/wiki/Users#create-a-user
----
Ross Scroggs
***@***.***
