### ISSUE TITLE
[Improvement] Add/remove "sent by" indication for delegation

### ISSUE THREAD

**Issue by teorouge** [taers232c/GAMADV-XTD3#390]
Hello, in Gmail there's an option to show the address and the person who sent it or to show the address only, can you adjust that via GAM? If that's not the case, can you add a toggle to do that?

![Auto Generated Inline Image 1](https://github.com/taers232c/GAMADV-XTD3/assets/10339867/6f019b50-432a-4ac2-810e-6307b0a441d5)

Thanks

**Comment by taers232c** [comment]
There is no API access for this, you have to allow the user to change this value in the admin console and then instruct the users to change the setting;

Admin Console/Apps/Google Workspace/Gmail/User Settings/Mail delegation.

Ross
----
Ross Scroggs
***@***.***
