### ISSUE TITLE
sharing quota error in GAM

### ISSUE THREAD

**Issue by devanandkulla** [taers232c/GAMADV-XTD3#391]
We are trying to move user drives to shared drives for a number of users, and for all users move completed successfully except for one. Where we are getting the sharing quota error for some files and it is retrying 10 times on each file.

Error: 

Temporary Error: sharingLimitexceeded - rate limit exceeded. User message: "Sorry, you have exceeded your sharing quota.", Backing off: 60 seconds, Retry: 1/10

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation.

Ross
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
See: https://tecnobits.com/en/google-drive-error-the-sharing-quota-has-been-exceeded-how-to-fix-it/ <https://tecnobits.com/en/google-drive-error-the-sharing-quota-has-been-exceeded-how-to-fix-it/>

Ross
----
Ross Scroggs
***@***.***
