### ISSUE TITLE
[create user] Html tag chars such as "<" in random passwords not replaced with html entities like "&gt;"

### ISSUE THREAD

**Issue by Ludovic-Emo-Pyl-Tech** [taers232c/GAMADV-XTD3#392]
When using creating a user with random password, it might contain chars like "<" or ">".
These chars are not replaced with html entities like "&gt;", hence they are interpreted as html and not displayed to the end user which then uses a wrong password.

Could you please change GAM so that these chars are not used in the generated passwords, or replaced in the rendered html ?

Command example: gam create user [...] password random [...] notify [...]  subject [...]  from [...]  gdoc [...]  id [...]  html [...] 

Random password example:
- logged in the log txt file: F2ary<cKz)7!mX([@SZ6
- seen by the end user in the email client:  F2ary because chars from < are considered as an html tag

**Comment by taers232c** [comment]
This should be fixed in 6.67.19

The problem would occur even when a password was manually entered, e.g., password "abc<123>"

Ross
----
Ross Scroggs
***@***.***

**Comment by Ludovic-Emo-Pyl-Tech** [comment]
Hello,

Thank you for the update. I've successfully upgraded to version 6.67.19 and will conduct further tests during the creation of the next user account. As this is not a frequent task, please feel free to close the issue in the meantime.

Your ongoing support is greatly appreciated !

Best regards,
Ludovic
