### ISSUE TITLE
Using gam to add permissions for files in Shared Drives

### ISSUE THREAD

**Issue by chysteria** [taers232c/GAMADV-XTD3#397]
I am trying to clone the permissions for an external Google user to a set of files in a Shared Drive. I've used one of the Advanced Scripts to get a CSV with Owner, driveFileID, and emailAddress (existing user with permissions). I've modified the csv for the new user to be granted permissions and am using the following command:

gam csv [csv file] gam user "~Owner" add drivefileacl "~driveFileId" user "~emailAddress" role "~role" 

To which I'm getting this error for each line: 

Traceback (most recent call last):
  File "__init__.py", line 73072, in ProcessGAMCommand
  File "__init__.py", line 60193, in createDriveFileACL
  File "__init__.py", line 52540, in _validatePermissionOwnerType
TypeError: unsupported operand type(s) for -: 'str' and 'set'

But I think I'm goofing up somewhere because subbing in the values from the csv into the command also produces the same error.

My Setup:
GAMADV-XTD3 6.68.02 - https://github.com/taers232c/GAMADV-XTD3 - pyinstaller
Ross Scroggs <ross.scroggs@gmail.com>
Python 3.12.2 64-bit final
MacOS Sonoma 14.2.1 arm64

**Comment by taers232c** [comment]
Bug, it's fixed in 6.68.05

Ross
----
Ross Scroggs
***@***.***
