### ISSUE TITLE
permission inherited filter not working for secondary permission

### ISSUE THREAD

**Issue by lucidheart** [taers232c/GAMADV-XTD3#398]
In attempting to audit my shared drives, I've encountered a situation where the "pm inherited false em" is not properly working.

Essentially, if I run the command "gam user user@domain.com print drivefileacl ###### oneitemperrow", it produces a result of a dozen or so.  Of which, ONE of the results is a member of the team drive, but ALSO has a secondary permission that duplicates the permission they already have a member of the team drive.  In the results of the query, the second permissions is listed with a one (1), including permission.permissionDetails.1.inherited where the result is "False".  The result confirms it is not an inherited permission.

However, when I run the same command above, adding the permission filter "gam user user@domain.com print drivefileacl ###### oneitemperrow pm inherited false em", this produces zero results.  This should in fact produce the one result that contains the augmented permission.

I'm looking at a workaround of having to filter through acls that have more than a single result to locate these unwanted duplicate permissions.  It would of course be better if gam could just find them for me using the filter.

**Comment by taers232c** [comment]
Richard,

Send me a Meet/Zoom invitation.

Ross
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
6.68.08

Updated `gam <UserTypeEntity> print filelist|drivefileacls|shareddriveacls ... oneitemperrow` to print
ACLs with multiple permission details on separate rows for each basic permission/permission detail combination.
This case occurs when a member of a Shared Drive has access to a file and also has explicitly granted access to the same file.

Added `permtype member|file` to `<PermissionMatch>` that allows determining whether an ACL on a Shared Drive file was
derived from membership or explicitly granted.
