### ISSUE TITLE
Add "not" mechanisms to established commands

### ISSUE THREAD

**Issue by chromestrong** [taers232c/GAMADV-XTD3#401]
Adding a "NOT" mechanism would be very useful in GAM for the established commands.

For example (s):

```

NOT + domain

gam print users not domain example.com todrive
//this command would print all users that did not have an example.com suffix.

gam print aliases not domain example.com todrive
//this command would print all aliases that did not have an example.com suffix.

gam print addresses not domain example.com todrive
//this command would print all addresses that did not have an example.com suffix.

NOT + group
//this command option would print all accounts that were not a member of the given group

NOT + OUs
//this command option would print all accounts that were not a member of the given OU.

NOT + User
//this command option would print all accounts with the exception of the given user account.

```

**Comment by chromestrong** [comment]
If NOT is problematic then adding a bang "!" to the established commands is an option too.

gam print users !domain example.com todrive
gam print aliases !domain example.com todrive
gam print addresses !domain example.com todrive
etc etc etc

**Comment by taers232c** [comment]
Eric,

The APIs have no support for these operations, you have to have GAM perform the filtering.
See: https://github.com/taers232c/GAMADV-XTD3/wiki/CSV-Output-Filtering#column-row-filtering' <https://github.com/taers232c/GAMADV-XTD3/wiki/CSV-Output-Filtering#column-row-filtering'>


gam config csv_output_row_drop_filter "primaryEmail:regex:domain.com" print users

gam config csv_output_row_drop_filter "Alias:regex:domain.com" print aliases

gam config csv_output_row_drop_filter "Email:regex:domain.com" print addresses

gam config csv_output_row_drop_filter ***@***.***$" all users print groups

gam config csv_output_row_drop_filter "orgUnitPath:regex:'/Test'" print users fields ou

gam config csv_output_row_drop_filter ***@***.***$" print users

Ross
----
Ross Scroggs
***@***.***

**Comment by chromestrong** [comment]
Okay, I was just seeing if there was a way to incorporate that functionality without having to filter the csv output.

**Comment by taers232c** [comment]
Here's what the API supports: https://developers.google.com/admin-sdk/directory/v1/guides/search-users <https://developers.google.com/admin-sdk/directory/v1/guides/search-users>

Ross
----
Ross Scroggs
***@***.***

**Comment by chromestrong** [comment]
I understand, but to make this simpler for the admin: Could the use of the not mechanisms be a shortcut to the csv filters that you have added outside of the API?

**Comment by taers232c** [comment]
No.

You can predefine the filters in gam.cfg and reference them on the command ine.

See: https://github.com/taers232c/GAMADV-XTD3/wiki/Meta-Commands-and-File-Redirection#select-output-filter-section <https://github.com/taers232c/GAMADV-XTD3/wiki/Meta-Commands-and-File-Redirection#select-output-filter-section>

[und]
csv_output_row_drop_filter "primaryEmail:regex:domain.com <http://domain.com/>"

gam selectfilter und print users

Ross
----
Ross Scroggs
***@***.***

**Comment by chromestrong** [comment]
So the shortcut already exists, but its just not being used.  Got it.  Well that sucks.

**Comment by taers232c** [comment]
I'm not sure what you mean, sned me a Meet/Zoom invitation.

Ross
----
Ross Scroggs
***@***.***
