### ISSUE TITLE
GAM Update User and Create User is not following case sensitivity for email addresses

### ISSUE THREAD

**Issue by KSchmeeds** [taers232c/GAMADV-XTD3#403]
Gam Version 6.71.15

When using gam create user or gam update user, the email address is always lowercased even if provided capital letters in the input.

Steps to reproduce:

gam create user email First.Last@domain.com

Observed behavior:

A user gets created in Google with the case of first.last@domain.com

Expected behavior:

A user gets created in Google with the case of First.Last@domain.com

**Comment by taers232c** [comment]
See: https://support.google.com/mail/answer/9211434?hl=en <https://support.google.com/mail/answer/9211434?hl=en>

Google converts uppercase characters to lowercase.

Ross
----
Ross Scroggs
***@***.***
