### ISSUE TITLE
Google Meet hardware SKU

### ISSUE THREAD

**Issue by jay-eleven** [taers232c/GAMADV-XTD3#405]
Hi Ross!

I just found a new SKU name / SKU ID combo that you might want to add to the known [SKU list](https://github.com/taers232c/GAMADV-XTD3/wiki/Licenses#license-products-and-skus).

SKU name: Google Meet hardware
SKU Id: Google-Hangouts-Software
Suggested abbreviations (consistent with other Meet SKUs): meethardware, googlemeethardware

It showed up this month:

```
xxx.com,Google Meet hardware,New commitment,yyyy,Mar 4,Mar 4,l,zzzzz,n.n
```
In turn, the Reseller API returned this:

```
...
      "skuId": "Google-Hangouts-Software",
...
      "status": "ACTIVE",
      "skuName": "Google Meet hardware",
...
```

**Comment by taers232c** [comment]
Jay,

Thanks, do you know what the product ID is?
> "skuId": "Google-Hangouts-Software",
> "skuName": "Google Meet hardware",
Interesting: the Id is software and the name is hardware.

Ross

----
Ross Scroggs
***@***.***

**Comment by jay-eleven** [comment]
The [Channel Services API products.list method](https://cloud.google.com/channel/docs/reference/rest/v1/products/list) says:
```
{
  "products": [
    {
      "name": "products/S2VSgM3Tlzklpc",
      "marketingInfo": {
        "displayName": "Google Meet Global Dialing",
        "description": "Expand the telephony coverage for Google Meet to allow easier access to video calls. \n      \n      \u003ca target='_blank' href='https://support.google.com/a/answer/10162808'\u003e\n    Learn more\u003c/a\u003e",
        "defaultLogo": {
          "content": "https://ssl.gstatic.com/apps/cpanel/resources/img/google_meet_logo_64.svg",
          "type": "MEDIA_TYPE_IMAGE"
        }
      }
    },
...
    {
      "name": "products/UL90w5EVpKxE2g",
      "marketingInfo": {
        "displayName": "Google Meet hardware",
        "description": "Video conferencing solution that enables colleagues to meet and collaborate, no matter where they are. Includes Chromebox, touchscreen, camera, and speakermic",
        "defaultLogo": {
          "content": "https://www.gstatic.com/images/branding/product/2x/meet_2020q4_64dp.png",
          "type": "MEDIA_TYPE_IMAGE"
        }
      }
    },
...
  ]
}
```
I deliberately deleted the product names not related to Meet and was left with global dialing and hardware.

So, `Google Meet hardware` is the product name you want to use.

Coincidentally, this is the same as the SKU name. Again, using the [Channel Services API products.skus.list method](https://cloud.google.com/channel/docs/reference/rest/v1/products.skus/list):

```
{
  "skus": [
    {
      "name": "products/UL90w5EVpKxE2g/skus/Un57jN19ALJEAP",
      "marketingInfo": {
        "displayName": "Google Meet hardware",
        "description": "Google Meet hardware lets you enroll and manage all your Google Meet hardware devices.",
        "defaultLogo": {
          "content": "https://www.gstatic.com/images/branding/product/2x/meet_2020q4_64dp.png",
          "type": "MEDIA_TYPE_IMAGE"
        }
      },
      "product": {
        "name": "products/UL90w5EVpKxE2g",
        "marketingInfo": {
          "displayName": "Google Meet hardware",
          "description": "Video conferencing solution that enables colleagues to meet and collaborate, no matter where they are. Includes Chromebox, touchscreen, camera, and speakermic",
          "defaultLogo": {
            "content": "https://www.gstatic.com/images/branding/product/2x/meet_2020q4_64dp.png",
            "type": "MEDIA_TYPE_IMAGE"
          }
        }
      }
    }
  ]
}
```
This last response makes it clear both product name and SKU name are the same.

**Comment by taers232c** [comment]
Jay,

Here's what I have for Google Meet Dialing
_PRODUCTS = {
...
  '101036': 'Google Meet Global Dialing',
...

_SKUS = {
...
  '1010360001': {
    'product': '101036', 'aliases': ['meetdialing','googlemeetglobaldialing'], 'displayName': 'Google Meet Global Dialing'},

What I need are the equivalents of product ID (101036) and SKU ID (1010360001)
Ross
----
Ross Scroggs
***@***.***

**Comment by jay-eleven** [comment]
Interesting, those values are not provided by any Google API and they're missing from the official Google documentation too... Hmmm... I'll leave this issue open while I try to figure out this information. 

Thanks Ross.
