### ISSUE TITLE
Export Threads/Messages missing many emails

### ISSUE THREAD

**Issue by lifers5555** [taers232c/GAMADV-XTD3#413]
GAM 6.76.05

Perform a search in GMail and put 800+ messages into a label _Export.

gam user user@domain.com.au export threads matchlabel _Export targetfolder "c:\export\user@domain.com.au"

GAM only exports 5 messages.

If I change it to:
gam user user@domain.com.au export messages matchlabel _Export targetfolder "c:\export\user@domain.com.au"

it exports only 1 message.

gam user user@domain.com.au show messages matchlabel _Export
results in:
User: user@domain.com.au, Show 800 Messages
  Message: 18da47929a04733e (1/800)

**Comment by taers232c** [comment]
Use the option: maxtoexport N
N defaults to 1
N = 0 export all messaages
N > 0 export no more that N messages

Ross
----
Ross Scroggs
***@***.***

**Comment by lifers5555** [comment]
Jesus Ross, that was a bit quick! I only just figured that out myself and was about to retract the ticket.

Thanks for your amazing tool and fast support!
