### ISSUE TITLE
Possible bug - gam report user user hangs if user does not exist

### ISSUE THREAD

**Issue by al3xcooper** [taers232c/GAMADV-XTD3#415]
Hi,

It could be me, but if I run the command to report user activity with an account that I know doesn't exist i.e 

`gam report user user dadasdasdaas@domain.com
Getting Reports for dadasdasdaas@domain.com`

gam seems to hang and I have to use control-c to exit (using GAMADV-XTD3 6.76.05 on Windows 11)

**Comment by taers232c** [comment]
It's not hung, it's calling the API 180 times backing up day by day looking for data.

Ross
----
Ross Scroggs
***@***.***

**Comment by al3xcooper** [comment]
ah thanks Ross, it's me not being patient
