### ISSUE TITLE
New Admin Please help.

### ISSUE THREAD

**Issue by gpearl-work** [taers232c/GAMADV-XTD3#417]
Sorry if some of these questions are redundant but I was newly given admin access.  Are there any commands that I should run to help validate health of what I have been handed (External sharing, email quota, disk quota, billing, etc...)

I am using 
gam print users allfields - but it only shows active users not suspended.

I am getting the filelist for users (gam all users show filelist) but again it is only shows active

What is the command to list all groups and all files in all groups.

With the filelist is there a query that will show just files that are shared externally (outside of my domain)?

I have both gam (6.58) and gameadv (6.76.15) working.

**Comment by taers232c** [comment]
Advancd GAM is a superset of Standard GAM, all of my replies are for Advanced GAM

> gam print users allfields - but it only shows active users not suspended.
> 
This is not correct, all users are shown. Look at the suspended column.
See: https://github.com/taers232c/GAMADV-XTD3/wiki/Users#display-information-about-multiple-users

> I am getting the filelist for users (gam all users show filelist) but again it is only shows active
> 

You want: gam all users_susp_ns show filelist
See: https://github.com/taers232c/GAMADV-XTD3/wiki/Collections-of-Users#user-type-entity
See: https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Drive-Files-Display#display-file-list

> What is the command to list all groups and all files in all groups.
> 
gam print groups
https://github.com/taers232c/GAMADV-XTD3/wiki/Groups

Files are associated with users, not groups.

> With the filelist is there a query that will show just files that are shared externally (outside of my domain)?
> 
See: https://github.com/taers232c/GAMADV-XTD3/wiki/Permission-Matches

gam all user sprint filelist fields id,name,mimetype,basicpermissions pm not domain mydomain.com <http://mydomain.com/> em pmfilter oneitemperrow

Ross

----
Ross Scroggs
***@***.***

**Comment by gpearl-work** [comment]
Thank you so much for the fast and comprehensive response.  I have lots to learn on this.

I did have to change the commands a little to get them to work.  I am putting the updated command in this response just incase anyone else is looking for the same type of command.

1st Command
gam all users_ns_susp show filelist allfields 

2nd Command
gam all users_ns_susp print filelist fields id,name,mimetype,basicpermissions pm not domain domain.com em pmfilter oneitemperrow
