### ISSUE TITLE
Delete sharedrive with items inside

### ISSUE THREAD

**Issue by pdewas** [taers232c/GAMADV-XTD3#42]
Hi Ross, 

Thank you for your amazing job ! 

I try to delete a sharedrive with this command : 
`gam user xxx@xxx.com delete teamdrive idxxx`

And the result : 
`User: xxx, Shared Drive ID: xxx, Delete Failed: This resource cannot be deleted because it has children`

Do we have to delete previously all the files and folders inside, then empty the trash and run the command? 

Thank you
Pierre

**Comment by taers232c** [comment]
Pierre,

That's correct, you can't delete a shared drive unless it's empty. This is the same in the API and online.
In drive.google.com, right-click on a Shared Drive and you'll see that "Delete shared drive" is disabled if the drive is not empty.

Ross
--
ross.scroggs@gmail.com

**Comment by pdewas** [comment]
Perfect thanks !
