### ISSUE TITLE
Free licenses are not counted?

### ISSUE THREAD

**Issue by Nikolay-Avanesyan-Borzo** [taers232c/GAMADV-XTD3#421]
Hello! Can you check is that ok - with command:
gam user USER_EMAIL print licenses
I try to get all uses licenses, but it show only paid licenses, free one as Cloud Identity Free or Chrome Browser Cloud Management are not includet to the list - is that ok as should it work?

![image](https://github.com/taers232c/GAMADV-XTD3/assets/173061832/a235de4f-1bc9-4499-b0b6-85525ff43c8d)

user have this one licenses
![image](https://github.com/taers232c/GAMADV-XTD3/assets/173061832/c4d9657a-4572-4a15-a1b9-16f885043831)

btw is there a was to get full amout of licenses subscription from google workspace - didn't find it in the wiki, find out only how to see assigned licenses

thanks!

**Comment by taers232c** [comment]
I'm not a license export but I believe that the License API only shows pis licenses.
The API only shows assigned licenses, I don't know of a way to see total licenses.

You may want to post you question to the GAM discussion group as there are people there mush more knowledgeable than me about licenses.

Ross
----
Ross Scroggs
***@***.***

**Comment by Nikolay-Avanesyan-Borzo** [comment]
Also noticed that it show only paid licenses - same story if receive this data via api without gam
Looks like this data can be received via resseler api if they enable it
thanks!
