### ISSUE TITLE
Google Mail Migration (New)

### ISSUE THREAD

**Issue by Connor1304** [taers232c/GAMADV-XTD3#424]
hey I just wanted to see if there was a way to utilise google's new gmail migration tool via gam as appose to using got-your-back?

**Comment by taers232c** [comment]
Send me a link to the description of the new tool.

Ross
----
Ross Scroggs
***@***.***

**Comment by Connor1304** [comment]
https://support.google.com/a/answer/14014035?hl=en

**Comment by taers232c** [comment]
I don't see anything in the document that talks about API access so Gam wouldn't be able to help.

Ross
----
Ross Scroggs
***@***.***

**Comment by Connor1304** [comment]
All good thought it was worth a shot thank you!

**Comment by github-mercuryprint** [comment]
I know the original user closed this issue but as I read about this
feature, there is a linked page called Get ready to migrate and when you
click on that the API is mentioned.

https://support.google.com/a/answer/14012274#getready:~:text=If%20you%27re%20migrating%20from%20Google%20Workspace%2C%20you%20don%27t%20need%20to%20turn%20on%20IMAP%20in%20your%20source%20or%20target%20account.%20The%20new%20data%20migration%20service%20uses%20the%20Gmail%20API%20to%20migrate%20data
.

**Comment by taers232c** [comment]
My old eyes aren't what they used to be, sned me a line of text I can search for on the page.

Thanks

Ross
----
Ross Scroggs
***@***.***

**Comment by taers232c** [comment]
I see it now, the migration service uses the Gmail API to read messsges, there is no migration in the API itself.

Ross
----
Ross Scroggs
***@***.***
