### ISSUE TITLE
KeyError on updating calendar events

### ISSUE THREAD

**Issue by patdon9722** [taers232c/GAMADV-XTD3#426]
Hi,

I am trying to update all events on a calendar after today to remove a certain attendee.  I get the KeyError below.

GAM 6.77.13

![image](https://github.com/user-attachments/assets/086b6f96-f0ad-4b90-a17e-e039147239dc)

**Comment by taers232c** [comment]
Patrick,

I can duplicate the problem, I'll fix.

Ross
----
Ross Scroggs
***@***.***

**Comment by patdon9722** [comment]
Thank you Ross!

**Comment by taers232c** [comment]
Fixed in 6.79.06
----
Ross Scroggs
***@***.***

**Comment by patdon9722** [comment]
Thanks!
