### ISSUE TITLE
Slow on MacOS Sonoma 14.6 M1 Apple Silicon ARM

### ISSUE THREAD

**Issue by gordonmcdowell** [taers232c/GAMADV-XTD3#427]
If I simply type: gam
...it takes about 10 seconds to respond. All commands take about 10 seconds.

"gam" response includes...

GAMADV-XTD3 6.79.05 - https://github.com/taers232c/GAMADV-XTD3 - pyinstaller
Python 3.12.4 64-bit final
MacOS Sonoma 14.6 x86_64
Path: /Users/gordonmcdowell/bin/gamadv-xtd3

...does x86_64 mean I'm not running ARM code?

It has been slow for a long time... I'm not saying any particular version is suddenly slow.

**Comment by gordonmcdowell** [comment]
My MacOS terminal was i386 instead of arm64. Nevermind.

**Comment by taers232c** [comment]
> MacOS Sonoma 14.6 x86_64 - Intel code
> 
----
Ross Scroggs
***@***.***
