### ISSUE TITLE
gam print cros issue

### ISSUE THREAD

**Issue by bffive** [taers232c/GAMADV-XTD3#43]
First of all, Ross, thanks so much for all that you do. I rely heavily on your documentation to get my job done and I'm forever grateful.

I have been using this modification of the gam print cros command every since the chromebookinventory add-on was disabled. I know Kim made something and maybe I should just use that instead, but, using the GAM command has been getting the job done for me. I ordered it as follows:
gam print cros orderby lastsync fields orgUnitPath,annotatedUser,annotatedLocation,annotatedAssetId,notes,serialNumber,macAddress,ethernetMacAddress,deviceid,status,model,firmwareversion,lastsync,osversion,bootmode,supportenddate todrive

I last used it on Feb 12 and had gamadv-xtd3-4.98.14-windows-x86_64 installed. I went to use it yesterday, and some times I get 402 results, sometimes 602, sometimes 1102, but never the 6152 total devices no matter what their state. I have the device_max_results = 200 and installed gamadv-xtd3-4.99.20-windows-x86_64 yesterday and gamadv-xtd3-4.99.22-windows-x86_64 today with no difference. If I run the same command and remove the "todrive" it still returns a random amount of results every time. Lastly, if I run gam print cros todrive or gam print cros allfields todrive it works without issue.

**Comment by taers232c** [comment]
Can you call me on Google Hangouts or send a Meet invitation?

**Comment by taers232c** [comment]
Curious. Drop the todrive for a moment.
I wonder if its some specific field that's messing things up.
Issue the following command, dropping a field on each run, at some point do you get 6152 devices?

gam redirect csv ./cros.csv print cros orderby lastsync fields orgUnitPath,annotatedUser,annotatedLocation,annotatedAssetId,notes,serialNumber,macAddress,ethernetMacAddress,deviceid,status,model,firmwareversion,lastsync,osversion,bootmode,supportenddate

**Comment by taers232c** [comment]
I'm seeing strange behavior as well, I'm investigating.
