### ISSUE TITLE
Update gmail labels

### ISSUE THREAD

**Issue by iKeqing** [taers232c/GAMADV-XTD3#435]
Hi Ross,

How can we update the exisiting Gmail label to nest under another label?

As per https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Gmail-Labels#update-a-labels-settings we can only update messagelistvisibility, labellistvisibility and color? Is there any way that we can update the label nest to another label as well?

Thanks for your help in advance.

Sincerely,

KQ

**Comment by taers232c** [comment]
See: https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Gmail-Labels#change-label-names

To nest Foo under Goo:
gam user ***@***.*** update label search "(^Foo$)" replace "Goo/\1"

Test with dummy labels

Ros
----
Ross Scroggs
***@***.***

**Comment by iKeqing** [comment]
Thanks Ross, it works like charm!
