### ISSUE TITLE
Question on print users query by EmployeeID

### ISSUE THREAD

**Issue by iKeqing** [taers232c/GAMADV-XTD3#436]
Hi There,

I tried to use `gam print users queries "E1108" fields employeeid` or `gam print users queries "E1108" fields externalids` but in vain, it always getting result as below, may I know what's the correct command to query by employeeid?

Getting all Users that match query (query="E1108"), may take some time on a large Google Workspace Account...
Got 0 Users:  -
primaryEmail,externalIds

Attachment: I do have the E1108 in my admin console.
![image](https://github.com/user-attachments/assets/37d84d4c-7c3a-47d8-ae95-08a795bc31db)

Thanks in advance.

**Comment by taers232c** [comment]
See: https://developers.google.com/admin-sdk/directory/v1/guides/search-users
> gam print users query "externalId='E1108'" fields employeeid 
> 

----
Ross Scroggs
***@***.***

**Comment by iKeqing** [comment]
Thanks Ross
