### ISSUE TITLE
Windows x64 - GAMERROR: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by damionwilliams** [taers232c/GAMADV-XTD3#44]
Hi Ross,

Thanks again for all your work on this script, it's appreciated globally!

I'm seeing an issue on Windows devices (presume all but Windows 10 Pro v1909 here) when running multiprocess commands on large amount of users.

GAMADV-XTD3 4.99.25 - https://github.com/taers232c/GAMADV-XTD3
Ross Scroggs <ross.scroggs@gmail.com>
Python 3.8.1 64-bit final
google-api-python-client 1.7.11
httplib2 0.16.0
oauth2client 4.1.3
Windows 10 10.0.18362   AMD64

gam config redirect csv ./tokenslist.csv multiprocess csv userlist.csv gam user print tokens
(didnt auto_batch_min this)

When it gets up to 49K users the tool will get stuck in a loop:
ERROR: File: C:\Users\user\.gam\oauth2.txt, [Errno 24] Too many open files: 'C:\\Users\\user\\.gam\\oauth2.txt.lock'

This will happen multiple times and then it will just repeat the vague 
ERROR: [Errno 24] Too many open files
ERROR: [Errno 24] Too many open files

again and again etc.

Doesnt happen on ubuntu

Can reproduce if needed for extra debug logs, just takes a while :) Be great to solve this if you can!

Thanks
Damion

**Comment by taers232c** [comment]
Damion,

Call me on Google Hangouts or send a meet invitation.

Ross

**Comment by taers232c** [comment]
Damion,

Contact me so we try try to figure out what's going on.

Ross

**Comment by taers232c** [comment]
Damion,

If this is still an issue, let me know.

Ross
