### ISSUE TITLE
Updating ChromeOS Devices using the GAM tool

### ISSUE THREAD

**Issue by HBogart2024** [taers232c/GAMADV-XTD3#444]
I am trying to script changes and updates to ChromeOS Devices using the GAM tool.  In the tool, I am trying to update the Notes, AssetID, annotatedLocated fields to either clear out the existing data or update the data to other values.

One of the things I noticed when doing this, the GAM tool errors on Null values.  I can't find any documentation on how to clear out the value in a field without having to enter in a space for the value.  Which is not clearing the data out, it's configuring it to a space.

Command I am using:

GAM Update CROS "< GUID value for the device >" Notes ""

Error
GAM: Command Gam.exe Update CROS <GUID Device Value> Notes >>><<<
Error:  Missing Argument: Expected <string>

Is there a Null, IsNull, IsEmpty, Empty, $Null, "" or some other value we can supply other than "Space" " " to clear this out?  the only way I have found to truly clear the value, is through the Google Admin Console.  

Note, we can set it to " " and it accepts it.  But this is setting the field to a Space Bar key and not truly empty.

**Comment by taers232c** [comment]
Are you in PowerShell?

See: https://github.com/taers232c/GAMADV-XTD3/wiki/Command-Line-Parsing

In PowerShell, if you want an empty string argument, you must enter: `"`"

Ross
----
Ross Scroggs
***@***.***

**Comment by HBogart2024** [comment]
Yes!  I will go ahead and try that!

**Comment by HBogart2024** [comment]
this resolved the issue.  Just missed the documentation regarding the Command Line Parsing.
