### ISSUE TITLE
print users include deleted accounts

### ISSUE THREAD

**Issue by muzzol** [taers232c/GAMADV-XTD3#451]
I'm not sure if this is a bug or if I'm missing something but when I perform a list of all accounts with

`gam print users
`

it includes deleted users and I can't find a way to filter them out.

I'm also not able to see any equivalent to **issuspended** like isdeleted, or the oposite of **deleted_only**. do they exist?

my use case is that I get a list of all current active users and I perform some actions on each account (backups, notifications, modifications...).

thanks for your time.

**Comment by taers232c** [comment]
gam print users > allusers.csv
gam print users deletedonly > deletedusers.csv

Are you seeing users in deletedusers.csv in allusers.csv?

Ross
----
Ross Scroggs
***@***.***
