### ISSUE TITLE
Permission match pmtype not working

### ISSUE THREAD

**Issue by joalcorn** [taers232c/GAMADV-XTD3#452]
Using GAMADV-XTD3 7.01.04. Attempting to enumerate file permissions using the command below:

```gam redirect csv ./StillSharedDriveFIlesAcls.csv multiprocess csv ./SharedDriveACLsAllExternal.csv gam user admin@example.com print filelist select teamdriveid "~id" pm domainlist example.com inherited false pmtype file em fields id,name,driveid```

I keep getting the following error:

```2024-12-04T21:50:50.198+00:00,0/40,Waiting for 3 running processes to finish before terminating, wait limit unlimited seconds
Command: gam user admin@example.com print filelist select teamdriveid <redacted> pm domainlist example.com inherited false >>>pmtype<<< file em fields "id,name,driveid"

ERROR: Invalid argument
Help: Syntax in file /Users/joalcorn/bin/gamadv-xtd3/GamCommands.txt
Help: Documentation is at https://github.com/taers232c/GAMADV-XTD3/wiki
```

I have verifed that I am actually running 7.01.04 and not running a different copy on an earlier version.

SharedDriveACLsAllExternal.csv has a list of all Shared drives that no longer have a domain member as a shared drive member or manager, based on the steps from the wiki: https://github.com/taers232c/GAMADV-XTD3/wiki/Shared-Drives#clean-up-scammed-shared-drives

Removing `pmtype file` and the command runs as expected.

**Comment by taers232c** [comment]
Documentarion error, change pmtype to permtype.

Ross
----
Ross Scroggs
***@***.***
