### ISSUE TITLE
5.00.12 Python Error after upgrading

### ISSUE THREAD

**Issue by NoGoCodeHunter** [taers232c/GAMADV-XTD3#48]
First time user of GAMADV, so no expert by any means. Have been using GAM for over 5 years though.

Installed 4.94.10 and had it working. Getting an error on the GAM CREATE CONTACT so decided to upgrade to the latest version, 5.00.12 and was unable to get it to run. The following error was produced:

> Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller-4.0.dev0+3e6f7dc709-py3.8.egg\PyInstaller\loader\rthooks\pyi_rth_certifi.py", line 13, in <module>
  File "C:\python\lib\site-packages\pyinstaller-4.0.dev0+3e6f7dc709-py3.8.egg\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "ssl.py", line 98, in <module>
ImportError: DLL load failed while importing _ssl: The specified module could not be found.
[12152] Failed to execute script pyi_rth_certifi

Downloaded and installed 5.00.11 and code ran without any errors.

System is Windows 10
Installed Python 3.7 and 3.8 just to see if maybe I needed python installed. Didn't help.
When I upgrade, how I do it with GAM, is just download the latest zip and extract it to the folder. If required, I'll run any commands to update the project if needed. This seems to work for this version as well, but I see it has many more options.

**Comment by taers232c** [comment]
Call me on Google Hangouts or send a Meet invitation.

**Comment by taers232c** [comment]
See: https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-GAMADV-X-or-GAMADV-XTD

Basically you want to do:
gam update project
gam oauth create
gam user user@domain.com check serviceaccount

**Comment by NoGoCodeHunter** [comment]
Ross,

Sorry man, I thought I ran those commands, but clearly I didn't. This solved my original problem with the contacts problem I was having.

As for the upgrade to 5.00.12, if you still want a hangout, let me know. My time this evening is a bit complicated, could be available after 10:30 or anytime tomorrow. I'm in Sacramento so same time zone.

-Chris
