### ISSUE TITLE
Error 500: 500 - Internal Error Encountered

### ISSUE THREAD

**Issue by sharwoodrusd** [taers232c/GAMADV-XTD3#49]
Encountering a hard stop error when running "create course" command when copyfrom is included. Verified content is stored in a user's personal Google Drive and shared so that anyone with the link can view. Happy to provide screenshots, code snips, or anything else as needed.

**Comment by taers232c** [comment]
Someone else has seen the same issue, I'm working on it.

Ross
--
ross.scroggs@gmail.com

**Comment by sharwoodrusd** [comment]
Thank you sir!

Steven Harwood

*Manager, Instructional Technology*

INNOVATION*&*LEARNER ENGAGEMENT

Riverside Unified School District

Office - (951)788-7135 Ext. 80210 <(951)%20788-7135>

*Need assistance or have a question regarding Google/PowerSchool
Learning/Pearson/AR? Please fill out a Work Order @ *
*https://remote.rusd.k12.ca.us/techworks*
<https://remote.rusd.k12.ca.us/techworks>* and we will be happy to assist
you.*

**Comment by taers232c** [comment]
Steven,

Install 5.01.01, the error is now soft. The other user has a similar issue except that the data is on a Team Drive. What's your schedule in the next few days, I'd like to figure out what the issue is. Has this worked for you in the past?

Ross

**Comment by sharwoodrusd** [comment]
Hi Ross,
I ran through the update this morning. It got further this time with the copyFrom but it did get another error 500 and stopped when copying work from the old class to the new class. This is the first time that we have ever tried to do something like this because of the circumstances that we are currently in. Please feel free to email me directly if you're interested. Sharwood@riversideunified.org. I am happy to share more information offline. Thank you sir!

**Comment by taers232c** [comment]
Call me on Google Hangouts or send a Meet invitation.
--
ross.scroggs@gmail.com
