### ISSUE TITLE
Edit group subject prefix

### ISSUE THREAD

**Issue by schlomo** [taers232c/GAMADV-XTD3#50]
How can I edit the group subject prefix found under Settings → Email Options in the Classic Groups?
![image](https://user-images.githubusercontent.com/101384/78168767-c9cbbe00-7450-11ea-8414-92c627fa7c16.png)

I also didn't find that in the [Group Settings API](https://developers.google.com/admin-sdk/groups-settings/v1/reference/groups) but I found an [issue](https://issuetracker.google.com/issues/36758316) for that, please everybody star.

Does anybody know of a solution to automate that?

Maybe keep this issue open so that users can easily find it and go to star the issue for the missing API.

**Comment by taers232c** [comment]
Schlomo,

I also don't see it in the API, thus there is nothing GAM can do.

You might post your guestion to the Gam group to see if anyone has any ideas.

Ross
--
ross.scroggs@gmail.com
