### ISSUE TITLE
Crashing on filelist with a large number of results

### ISSUE THREAD

**Issue by jortony** [taers232c/GAMADV-XTD3#51]
Hello!
I'm experiencing crashes with large query results. I've tried using several different methods, but I haven't had success yet. Ultimately, I am trying to output all of the files which are shared from outside the organization. I have a pretty neat process, but it is choking sometimes on any output which contains more than 800k results. I think this has a high probability to be an issue with system resources, but I'm unsure. If you think it is too, I'll roll this into a forum post with more details regarding the resulting processes which I have found to be extremely efficient methods to mine the logs for data on a Windows platform. 

My local environment:
```
Windows10 1809
Powershell ISE version 5.1
```
Using this command:
```
gam redirect stdout $outfile multiprocess redirect stderr $errorfile multiprocess batch $batchfile showcmds true 2>> $stderrfile
```
Batch file contents:
```
gam user user@domain print filelist showownedby others fields id,title,permissions,owners.emailaddress
```

To troubleshoot, I broke the command into separate processes with batches of 1 to try and rule out any limitations of powershell. I've also tried to split stderr out in a couple of ways in the hopes it would catch the error or number of files before the error occurred. It crashes with several users in our domain with access to many files. 

Here's what was captured in the $errorfile log (stderr was very similar):
```
2020-04-03T13:37:36.661+00:00,0,Using 1 process...
2020-04-03T13:37:36.661+00:00,1,gam user user@domain print filelist showownedby others fields "id,title,permissions,owners.emailaddress"
2020-04-03T17:13:04.410+00:00,1,Complete
2020-04-03T17:13:04.425+00:00,0,Complete
```
Here's the Google Cloud Platform API usage over the duration of this users queries:
![image](https://user-images.githubusercontent.com/3673147/78389748-e844cd00-75a8-11ea-943c-3eb66a14706d.png)

Here's my local system resource usage as it crashed:
![image](https://user-images.githubusercontent.com/3673147/78390389-17a80980-75aa-11ea-8eb4-644a242832c2.png)

**Comment by taers232c** [comment]
Call me on Hangouts or send a Meet invitation.

Ross
ross.scroggs@gmail.com
