### ISSUE TITLE
Issue when trying to update custom schemas

### ISSUE THREAD

**Issue by dav1303** [taers232c/GAMADV-XTD3#52]
Hi

It seems there is an issue when I try to update custom schema data when users email address is longer than 64 characters

Can you check and let me know

Thanks

**Comment by taers232c** [comment]
Show me the command and the error, replace the user name characters with x'x but keep the length the same

Ross
--
ross.scroggs@gmail.com

**Comment by dav1303** [comment]
Hi

So sorry 

I have found my issue is into the source file.

BR
