### ISSUE TITLE
can't create oauth2.txt using gam oauth create

### ISSUE THREAD

**Issue by Grptxt** [taers232c/GAMADV-XTD3#55]
Hi, Hope someone can help?

After creating a new GAM project and then running GAM oauth create, i click the allow api access button and then get a Authorization error invalid request account restricted. i've attached a screen shoot of the error. 

i manage a number of domains, some have authorised without problems and some get the above error..i'm a little lost. it seems google has changed API permissions recently and i'm wondering whether this has anything to do with it. 
![error](https://user-images.githubusercontent.com/64086051/79884707-64367600-83ed-11ea-963f-36ef281cf499.JPG)

**Comment by Grptxt** [comment]
i've found the issue to be with Classroom Topics api, same as another post on this thread. i've now removed this from the list of API's to enable and the oauth file now gets created without error. if anyone has a solution to resloving the access denied classroom topics issue, do let me know...not to sure i want to log a call with google, its never been a great experience!!

**Comment by BeteB** [comment]
I have the same problem in the latest release.  I unchecked the Classroom topics to see if I could proceed, and now have a new error:  ERROR: The authentication flow failed (invalid verification code entered?): (mismatching_state) CSRF Warning! State not equal in request and response.  This is the latest version of Advanced GAM - just installed.

**Comment by taers232c** [comment]
Verify the following:
https://github.com/taers232c/GAMADV-XTD3/wiki/Authorization#introduction

I'm in California (PDT), send me a Meet/Zoom for tomorrow (Monday) morning after 7:45AM.

Ross
--
***@***.***

**Comment by ceidem** [comment]
Just in case someone stumbles on this as I did, the need to remove all the Classroom options is the way to get oauth2.txt created still.

**Comment by taers232c** [comment]
You only have to unselect one scope, these are good choices.
[ ] 38)  Email Audit API
[ ] 49)  Sites API

Ross
----
Ross Scroggs
***@***.***
