### ISSUE TITLE
gam print course-submissions student xxxxxx

### ISSUE THREAD

**Issue by HelloWorld502** [taers232c/GAMADV-XTD3#56]
Returns: User:``teacher1@domain.com``, Service not applicable/Does not exist

**Comment by taers232c** [comment]
Do: gam user teacher1@domain.com <mailto:teacher1@domain.com> check serviceaccount''
Update service account access

Ross
--
ross.scroggs@gmail.com

**Comment by HelloWorld502** [comment]
Yup. That worked. I went from GAM to GAMADV-XTD3...when I installed GAM, I
remember having to do that step, but GAMADV did not make me do it. Now I
know!

**Comment by taers232c** [comment]
To make sure you have all the power of GAMADV-XTD3, do:
gam update project
gam oauth create   (scopes 29 and 32 ar only used in special cases, you can leave them disabled)

Ross
--
ross.scroggs@gmail.com

**Comment by HelloWorld502** [comment]
Ross,

I was wondering if you ever cracked the nut for removing an orphaned
classroom?
https://groups.google.com/forum/#!msg/google-apps-manager/fAuYir7mHHI/X0wtEFWhBAAJ


My predecessor was in the habit of deleting accounts which resulted in 18
classrooms that have "Unknown user"

Executing this command:
gam update course ###### status archived

Returns this result:
Temporary error: internalError - Internal error encountered., Backing off:
16 seconds, Retry: 4/10

Should I just go straight to Google on this one?

Thanks,
Jim VF

P.S. Is there a better channel to communicate with you? I appreciate the
time you have taken so far to help me.

**Comment by taers232c** [comment]
Jim,

Straight to Google it is.

Ross

**Comment by HelloWorld502** [comment]
Ross,

Thanks! I'm on the support chat now...a lot of good that does. They told me
they don't support GAM and I was like...I'm not asking for help with GAM,
I'm trying to archive courses with unknown user.

Thanks,
Jim

**Comment by taers232c** [comment]
Call me on Hangouts or send a Meet invitation.

ross.scroggs@gmail.com
