### ISSUE TITLE
Get SpreadSheet Data in CSV

### ISSUE THREAD

**Issue by dav1303** [taers232c/GAMADV-XTD3#57]
Hi Ross

In V 5.02.03 you Added command to get Google Spreadsheet data in CSV format.

How do you done that and what is the exact result ? Do you still get One Line per rows corresponding to you sheet ?

Thanks

**Comment by taers232c** [comment]
This command gets data about spreadsheets themselves, not the data within them.
```
gam <UserTypeEntity> print sheet <DriveFileEntity> [todrive <ToDriveAttribute>*]
        [fields <SpreadsheetFieldList>] (range <SpreadsheetRange>)* [includegriddata [<Boolean>]]
	[formatjson] [quotechar <Character>]
```
Example:
```
gam user user@domain.com print sheets query "mimeType = 'application/vnd.google-apps.spreadsheet'" formatjson quotechar '"' fields sheets
```
The headers are: User,spreadsheetId,JSON
You get one row per sheet.

**Comment by dav1303** [comment]
Hi Ross
I just want to get the content of mu Spreadsheet in a csv file.

I think can get it using gam <UserTypeEntity> get drivefile to

Am i right ?

Thanks

**Comment by taers232c** [comment]
gam user user@domain.com get drivefile name TestSheet gsheet Sheet1 format csv
--
ross.scroggs@gmail.com
