### ISSUE TITLE
[FR] GCE usage

### ISSUE THREAD

**Issue by davidebelloni** [taers232c/GAMADV-XTD3#58]
Hi,
it would be nice if it were possible to use the tool from a GCE VM without download the service account but using the one associated to the VM.
I've found nothing about this setup, do you think that exist a workaround to permit it or that can be developed the required code?

Thanks

**Comment by taers232c** [comment]
David,

We'll have to talk about this as I'm not familiar with GCE VM. I'm in California (PDT), when could be a good time to connect via Hangouts or Meet? I'm generally available from 7:30AM (PDT) on.

Ross

**Comment by davidebelloni** [comment]
Hi Ross, 
thanks for your time!

If you want I'm available today or monday from 7:30AM to 9:00AM (PDT)
I'll call you with Hangouts to you gmail account

**Comment by taers232c** [comment]
Davide,

Call me now.

Ross
--
ross.scroggs@gmail.com

**Comment by davidebelloni** [comment]
Ok,
you have to accept invitation

**Comment by taers232c** [comment]
I don't see an invitation; try again or I can call you.
--
ross.scroggs@gmail.com

**Comment by davidebelloni** [comment]
davide.belloni@gmail.com
