### ISSUE TITLE
user print drivesettings issue

### ISSUE THREAD

**Issue by victor-creed** [taers232c/GAMADV-XTD3#59]
![image](https://user-images.githubusercontent.com/64491885/80517619-58016a00-8953-11ea-9947-e607614e7269.png)

Receiving error when running print drivesettings against a user. I am using gamadv-xdt3 v5.03.09 on Windows.

Thanks.

**Comment by taers232c** [comment]
This will be fixed shortly.

**Comment by taers232c** [comment]
Victor,

I apologize, the site where I build gam is hours behind but the build is finally complete.

Get 5.03.17, test and report backs.

Ross

**Comment by victor-creed** [comment]
Problem solved. Thank you sir!
