### ISSUE TITLE
Passlib 1.7 deprecated

### ISSUE THREAD

**Issue by highpointacademy** [taers232c/GAMADV-XTD3#6]
When creating a new user, I get the following :

`c:\gamwork>gam csv add_students.csv gam create user ~user_name first
name ~first_name lastname ~last_name password 'ChangeMe19'
Using 1 process...
gam.py:20966: DeprecationWarning: the method passlib.handlers.sha2_crypt.sha512_
crypt.encrypt() is deprecated as of Passlib 1.7, and will be removed in Passlib
2.0, use .hash() instead.
User: testy2.student@mydomain.com, Created`

**Comment by taers232c** [comment]
Fixed 4.82.01
--
ross.scroggs@gmail.com

**Comment by highpointacademy** [comment]
Confirmed that the fix is working for me (not that you needed me to confirm - HA!)

Thanks!
