### ISSUE TITLE
course update copyfrom course material

### ISSUE THREAD

**Issue by c0deweaver** [taers232c/GAMADV-XTD3#60]
The following command will copy everything except for course material. The material that is attempting to be copied over is Slides and Docs. (I did see the note about forms not copying) 

gam create course copyfrom <<template>> announcementstates "all" workstates "all" markpublishedasdraft true removeduedate true copytopics true teacher <<teacher>> name "TEMPLATE 102"

I feel like I am just missing an argument to make it happen.

**Comment by taers232c** [comment]
Shawn,

Call me on Google Hangouts or send a Meet invitation.

Ross
--
ross.scroggs@gmail.com

**Comment by c0deweaver** [comment]
This is a bug on google's end. Existing issue on their issue tracker.

https://issuetracker.google.com/issues/115421140
