### ISSUE TITLE
Shared Drive Support

### ISSUE THREAD

**Issue by nkabir** [taers232c/GAMADV-XTD3#62]
When I attempt to create a folder in a shared drive, gam claims the drive does not exist:

`$ gam user <user> create drivefile drivefilename demo mimetype gfolder parentid <parent_id>`

`User: <user>, Drive File Not Created: parentid: <parent_id>, Does not exist`

This works in https://github.com/jay0lee/GAM

Apologies if I looked over something obvious. The tool is much appreciated!

**Comment by taers232c** [comment]
Norman,

Call me on Google Hangouts or send a Meeti invitation.

Ross
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Norm,

This will work, I'll investigate why plain parentid doesn't.
> $ gam user <user> create drivefile drivefilename demo mimetype gfolder teamdriveparentid <parent_id>
> 
> 
Ross
--
ross.scroggs@gmail.com
