### ISSUE TITLE
"No user count data available."

### ISSUE THREAD

**Issue by SimonSmart1** [taers232c/GAMADV-XTD3#64]
When running the query "gam info domain" noticed over the last few weeks this has mostly returned "No user count data available." as one of the results. I've tested this across multiple instances of GAM on multiple domains.

**Comment by taers232c** [comment]
This was fixed in version 5.03.28, the current version is 5.03.34, please upgrade.
--
ross.scroggs@gmail.com

**Comment by SimonSmart1** [comment]
Thanks Ross!
