### ISSUE TITLE
Update page in classic sites?

### ISSUE THREAD

**Issue by nkabir** [taers232c/GAMADV-XTD3#66]
I cannot seem to find an example of how to update a page in classic sites. Ideally, I'd like to execute

gam update sites <SiteEntity> <SiteAttribute>+
https://github.com/taers232c/GAMADV-XTD3/wiki/Sites

with parameters that replace the content of a page with new content. But it's not clear if this is possible nor how the command should be structured.

**Comment by taers232c** [comment]
GAMADV-XTD3 has never had support for modifying classic site content.

Ross
--
ross.scroggs@gmail.com

**Comment by nkabir** [comment]
Apologies. My mistake. Is there any way to use this part of the API? Perhaps a different library if you happen to know of one?

https://developers.google.com/sites/docs/1.0/developers_guide_python#CreatingContent

Cheers,
--Norm

**Comment by taers232c** [comment]
I didn't find any in a quick Google search.
What are you trying to accomplish?

Ross
--
ross.scroggs@gmail.com

**Comment by nkabir** [comment]
Hi Ross. I'd like to update content in pages along the lines of what's described here:

https://patrick.wagstrom.net/weblog/2010/02/04/command-line-updating-pages-on-google-sites/
