### ISSUE TITLE
gamoauthurl.txt not generated during authentication flow

### ISSUE THREAD

**Issue by damionwilliams** [taers232c/GAMADV-XTD3#67]
Hi Ross,

When authorising gam with:
gam config no_browser true oauth create superadmin@domain.com
(or gam.cfg with no_browser = true)

When the url to authorise gam appears:
(The link may be copied from the file **<**C:\Tools\gamxtd**>**\gamoauthurl.txt rather than the screen.)
The txt file is not generated on windows or linux machines.

It would be great if this could be created, thank you!

Best Regards,
Damion

**Comment by taers232c** [comment]
Damion,

Fixed 5.04.05

Thanks for pointing out the problem,

Ross
--
ross.scroggs@gmail.com

**Comment by damionwilliams** [comment]
Ross you are a star, thank you!
