### ISSUE TITLE
gamoauthurl.txt different to url presented in console

### ISSUE THREAD

**Issue by damionwilliams** [taers232c/GAMADV-XTD3#68]
Hi Ross,

Sorry you just fixed this and I'm back again like the proverbial bad penny.

It looks like there are slight differences in the text string added to gamoauthurl.txt, part of it I can work around. The url in the text file misses:
&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob
just prior to the &scope= 's being passed. This results in :

Error 400: invalid_request
Missing required parameter: redirect_uri

When trying to use the url to perform the oauth2 authentication.

Even with that text injected though, when you look at the call, both the state code and the code_challenge code are different in the text file to the command you would traditionally copy and paste from the console:

Fore example the screen displays:

state=7cNxnXPmQ9DDZbQRAFr1pWLPp9ij2U&access_type=offline&login_hint=damionwilliams%40gafetest.com&prompt=consent&code_challenge=widcF_g9Yvixhk0ea62QgGPwyEgnFK0TnfZ_9IgQmxM&code_challenge_method=S256

yet the text file contains:
state=yX7f18Lmy1i9Wy4eyqklDuk5lGgDhp&access_type=offline&login_hint=damionwilliams%40domain.com&code_challenge=uE8sZHb4yv-0h2UfCnUvGUoK04GxtqBhSwvkFSgousE&code_challenge_method=S256

If you use the (modified) text file code with Google, you get this error:

Enter verification code: 4/0QHcdq8kXBhPeZHlpOSAViDVX6zWN0BSJ4K45MLdGg5ocCDscIpd4-M
Traceback (most recent call last):
  File "gam.py", line 46409, in ProcessGAMCommand
  File "gam.py", line 45729, in processOauthCommands
  File "gam.py", line 7609, in doOAuthCreate
  File "gam.py", line 7573, in doOAuthRequest
  File "gam.py", line 7539, in _run_oauth_flow
  File "google_auth_oauthlib\flow.py", line 411, in run_console
  File "google_auth_oauthlib\flow.py", line 285, in fetch_token
  File "requests_oauthlib\oauth2_session.py", line 360, in fetch_token
  File "oauthlib\oauth2\rfc6749\clients\base.py", line 421, in parse_request_body_response
  File "oauthlib\oauth2\rfc6749\parameters.py", line 431, in parse_token_response
  File "oauthlib\oauth2\rfc6749\parameters.py", line 438, in validate_token_parameters
  File "oauthlib\oauth2\rfc6749\errors.py", line 405, in raise_from_error
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Invalid code verifier.

Thank you again for your time

**Comment by taers232c** [comment]
Call me on Hangouts or send a Meet invitation.

**Comment by taers232c** [comment]
Working on it. The library doesn't generate the URL until it's running, there's no call to get it directly.

**Comment by taers232c** [comment]
Damion,

5.04.06

Ross

**Comment by damionwilliams** [comment]
Hi Ross,

Thank you for this again, sorry I'm on different hours so Meet is difficult.

Looks like its capturing a python call now and pumping out the string when no_browser true, in both the console output and the text file:
`https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=1231243424-34243243243243243243243242&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.announcements+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.topics+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.coursework.students+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.courses+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.profile.emails+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.profile.photos+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.rosters+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fclassroom.guardianlinks.students+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.read_only+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudprint+https%3A%2F%2Fwww.google.com%2Fm8%2Ffeeds+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.datatransfer+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.device.chromeos+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.customer+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.domain+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.group+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.device.mobile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.orgunit+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.resource.calendar+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.rolemanagement+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.userschema+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.user.security+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.user+https%3A%2F%2Fapps-apis.google.com%2Fa%2Ffeeds%2Fcompliance%2Faudit%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fapps.groups.migration+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fapps.groups.settings+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fapps.licensing+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.reports.audit.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.reports.usage.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification+https%3A%2F%2Fsites.google.com%2Ffeeds+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fediscovery&state=LzLEonXKQcNBRe996nOECKThNVSTkQ&writeGAMOauthURLfile=%3Cfunction+writeGAMOauthURLfile+at+0x7ff934444550%3E&access_type=offline&login_hint=damionwilliams%40domain.com&auth_url_callback=%3Cfunction+writeGAMOauthURLfile+at+0x7ff934444550%3E&prompt=consent&code_challenge=4yuWHGTlRXL2kQEJrJFLo9SDGEx6ir6Fn3bFRn3Se8A&code_challenge_method=S256`

The state and the challenge code are identical in the console and the text file however so that is now working thank you!

**Comment by taers232c** [comment]
Damion,

Good to hear; thanks for your efforts.

Ross
--
ross.scroggs@gmail.com

**Comment by damionwilliams** [comment]
I did nothing Ross other than annoy you! :o) And I meant to say, I realise now looking back it doesnt look it but I was trying to say while those other bits are fixed, anyone trying to use no_browser will be seeing this: 
writeGAMOauthURLfile=%3Cfunction+writeGAMOauthURLfile+at+0x7ff934444550%3E
In the url both in the console and the file! So sorry for this!

**Comment by damionwilliams** [comment]
Always a star Ross, thank you! Closing!
