### ISSUE TITLE
NameError: free variable 'writeURLtoFile' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by gjimenezf** [taers232c/GAMADV-XTD3#72]
When I use the command: gam user user@dmain.com check serviceaccount

I get this error:
NameError: free variable 'writeURLtoFile' referenced before assignment in enclosing scope

Tested with 5.05.09 and 5.05.08
Python 3.7.0

System time status
  Your system time differs from www.googleapis.com by less than 1 second    PASS
Service Account Private Key Authentication
  Authentication                                                            PASS
Service Account Private Key age; Google recommends rotating keys on a routine basis
  Service Account Private Key age: 43 days                                  WARN
Domain-Wide Delegation authentication:, User: admin@cti.espol.edu.ec, Scopes: 20
  https://mail.google.com/                                                  PASS (1/20)
  https://sites.google.com/feeds                                            FAIL (2/20)
  https://www.google.com/m8/feeds                                           FAIL (3/20)
  https://www.googleapis.com/auth/activity                                  PASS (4/20)
  https://www.googleapis.com/auth/apps.alerts                               PASS (5/20)
  https://www.googleapis.com/auth/calendar                                  PASS (6/20)
  https://www.googleapis.com/auth/classroom.announcements                   FAIL (7/20)
  https://www.googleapis.com/auth/classroom.coursework.students             FAIL (8/20)
  https://www.googleapis.com/auth/classroom.profile.emails                  FAIL (9/20)
  https://www.googleapis.com/auth/classroom.rosters                         FAIL (10/20)
  https://www.googleapis.com/auth/classroom.topics                          FAIL (11/20)
  https://www.googleapis.com/auth/cloud-platform                            FAIL (12/20)
  https://www.googleapis.com/auth/cloudprint                                FAIL (13/20)
  https://www.googleapis.com/auth/contacts                                  FAIL (14/20)
  https://www.googleapis.com/auth/drive                                     PASS (15/20)
  https://www.googleapis.com/auth/drive.activity                            FAIL (16/20)
  https://www.googleapis.com/auth/gmail.modify                              FAIL (17/20)
  https://www.googleapis.com/auth/gmail.settings.basic                      PASS (18/20)
  https://www.googleapis.com/auth/gmail.settings.sharing                    PASS (19/20)
  https://www.googleapis.com/auth/spreadsheets                              PASS (20/20)
Traceback (most recent call last):
  File "gam.py", line 46694, in ProcessGAMCommand
  File "gam.py", line 8759, in checkServiceAccount
  File "gam.py", line 8596, in authorizeScopes
NameError: free variable 'writeURLtoFile' referenced before assignment in enclosing scope

**Comment by taers232c** [comment]
Thanks, will be fixed shortly.

Ross
--
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Fixed 5.05.10
--
ross.scroggs@gmail.com
