### ISSUE TITLE
ERROR: config is not a valid argument for "gam"

### ISSUE THREAD

**Issue by oferzern** [taers232c/GAMADV-XTD3#75]
Hi,

I was just trying to upgrade from gam (was on latest version) to GAMADV-XTD3.
Using Windows 10 V.1909, chrome as the default browser, 

Almost finished the process as I followed this guide: https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM

On the last command, "gam config customer_id C01234567 domain domain.com timezone local no_update_check true save verify" (I've edited the command to fit the "gam info domain" details)
I'm getting an error stating that **config is not a valid argument for "gam"**

Did anyone encounter this before?

Thanks,
Ofer.

**Comment by oferzern** [comment]
Found the issue.
I missed a step

**Comment by JoepKleinmeulman** [comment]
@oferzern Any chance you remember the step you missed? If been looking at the same error for too long, just going for a hail mary here.

**Comment by taers232c** [comment]
See: https://github.com/taers232c/GAMADV-XTD3/wiki/How-to-Upgrade-from-Standard-GAM#windows
Scroll down to: Set system path and GAM configuration directory
