### ISSUE TITLE
ERROR: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by pdewas** [taers232c/GAMADV-XTD3#77]
Hello, 
I have this error when requesting with multiprocess with 25 thread on 130.000 users. 
**ERROR: [Errno 24] Too many open files**

`gam redirect csv ./calendardomainacl.csv multiprocess noheader csv users.csv gam config csv_output_row_filter "'scope.type:regex:^domain$'" user ~email print calendaracls ~email`

Thank you, 
Pierre

**Comment by taers232c** [comment]
Pierre,

Call me on Google Hangouts or send a Meet invitation.
I'm in California (PDT)

Ross
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
What OS are you on?
What version of GAMADV-XTD3 do you have? Versions 5.08.00+ may help.

**Comment by pdewas** [comment]
Thanks for your time ! 
Updating the version solve this issue !
