### ISSUE TITLE
Error while installing "`XCRYPT_2.0' not found"

### ISSUE THREAD

**Issue by thejestyr** [taers232c/GAMADV-XTD3#79]
When I try to install via "bash <(curl -s -S -L https://git.io/fhZWP)" everything starts off fine.  It downloads and starts the process:

Ask me about the browser - I answer yes
Gam is now installed, set up the api - I answer yes
Enter your admin email - I type in my admin email

then this...

Traceback (most recent call last):
  File "gam.py", line 121, in <module>
  File "/home/travis/python/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "crypt.py", line 6, in <module>
ImportError: /usr/lib/libcrypt.so.1: version `XCRYPT_2.0' not found (required by /tmp/_MEIDBLqd4/_crypt.cpython-38-x86_64-linux-gnu.so)
[163607] Failed to execute script gam
Project creation failed. Trying again. Say N to skip project creation.

If I type Y it just repeats, when I hit N it does this...

GAM is now installed. Are you ready to set up a Google API project for GAM? (yes or no) - I answer No

then...

You can create an API project later by running:

gam create project

Here's information about your new GAM installation:

Traceback (most recent call last):
  File "gam.py", line 121, in <module>
  File "/home/travis/python/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "crypt.py", line 6, in <module>
ImportError: /usr/lib/libcrypt.so.1: version `XCRYPT_2.0' not found (required by /tmp/_MEIbEM1eH/_crypt.cpython-38-x86_64-linux-gnu.so)
[163612] Failed to execute script gam
ERROR: Failed running GAM for the first time with 255. Please report this error to GAM mailing list. Exiting.

----------------------------------------

I am running Manjaro if that is relevant in anyway.  I only bring that up because I haven't had this issue in the past installing it on Ubunutu.

**Comment by taers232c** [comment]
I'm in California (PDT) and am available from 08:30 to 05:30.

Call me on Hangouts/Meet/Zoom and we'll figure out how to move forward.

Ross
ross.scroggs@gmail.com

**Comment by thejestyr** [comment]
Thanks for the quick support call.

For documentation purposes we ended up just manually installing a slightly older version of GAM.  Something with the libcrypt.so.1 that Manjaro was using at the time wasn't liking the current code base.
