### ISSUE TITLE
Not able to use Sendas

### ISSUE THREAD

**Issue by iKeqing** [taers232c/GAMADV-XTD3#80]
Hi,

I not able to use sendas function, will get “invalid arguments” error

**Comment by taers232c** [comment]
Without the command or the full error message it will be very hard to help.
Please post the command and the error message. You can substitute user@domain.com for the actual email address
if desired but do not alter the form of the command.

Ross

**Comment by iKeqing** [comment]
Hi Ross!

Enclosed my command below:
gam user userA@domain.com add sendas userB@domain.com name "ABC Incident" replyto userB@domain.com

will getting invalid arguments error

btw, can we setup group email as send as?

**Comment by taers232c** [comment]
https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Gmail-Send-As-Signature-Vacation#manage-sendas

Drop name, it is only used in update.
```
gam user userA@domain.com add sendas userB@domain.com "ABC Incident" replyto userB@domain.com
```

Yes you can use a group email address
