### ISSUE TITLE
`gam print group_members <group> includeDerivedMembership` on group with no sub-groups doesn't return all members

### ISSUE THREAD

**Issue by stephengale801** [taers232c/GAMADV-XTD3#82]
We are running `gam print group_members <group> includeDerivedMembership` and it returns 14 group members. This group does not include any sub-groups.
When we run `gam print group_members <group> recursive` 24 (expected results) members are returned, all with level 0.
Running the command without either flag returns the expected values.

**Comment by taers232c** [comment]
Call me on Hangouts/Meet/Zoom

ross.scroggs@gmail.com
