### ISSUE TITLE
dedup contacts not deleting duplicate contacts

### ISSUE THREAD

**Issue by LinU777** [taers232c/GAMADV-XTD3#85]
Hello.
I tried to delete the duplicated contacts with command, but it didn't work.
I created duplicated contact with same email and ran the script:

`gam user user@example.com dedup contacts`

output:

> Getting all Contacts for user@example.com
> Got 454 Contacts...
> User: user@example.com, Delete Duplicates maximum of 454 Contacts

But duplicated contact was not deleted.

gam version:

> GAMADV-XTD3 5.08.19 - https://github.com/taers232c/GAMADV-XTD3 - staticx
> Ross Scroggs <ross.scroggs@gmail.com>
> Python 3.8.5 64-bit final
> google-api-python-client 1.9.3
> httplib2 0.18.1
> Linux    x86_64

**Comment by taers232c** [comment]
I apologize, somehow this issue completely escaped my attention.
`dedup contacts` removes duplicate email addresses within a contact.
It does not delete contacts that have the same email address(es) as other contacts.

Ross
