### ISSUE TITLE
`gam user <UserEntity> add license 1010310002`   throwing error "ERROR: Got an unxepected keyword argument \"throw_reasons\""

### ISSUE THREAD

**Issue by stephengale801** [taers232c/GAMADV-XTD3#93]
Updated to the most recent version of GAM ADVX-TD3 this AM.  Suddenly getting the error.  This is preventing adding any Enterprise for Education licenses (haven't tried with other SKUs).

**Comment by stephengale801** [comment]
Screenshot when used in conjunction with `gam csvfile <filename>:<fieldname> sync license 1010310002`

![image](https://user-images.githubusercontent.com/14339317/94948597-cf0bd300-049c-11eb-9e58-9546d4431d0c.png)

**Comment by taers232c** [comment]
Will be fixed shortly.

**Comment by taers232c** [comment]
Fixed 5.12.10
