### ISSUE TITLE
Activities Report - Meet

### ISSUE THREAD

**Issue by dav1303** [taers232c/GAMADV-XTD3#95]
Hi

When I launch this command with different delimiter defined in my gam.cfg it is not working

gam.exe config csv_output_row_filter "meeting_code:regex:\^[A-Z]" report meet range 2020-10-05 2020-10-06 > D:\0-IN\Analyse_Meet\meet_details_man.csv

csv_output_column_delimiter = ;
csv_input_column_delimiter = ;
csv_output_field_delimiter = ';'

The output file still contains "," even when I change and select another config

Thanks

**Comment by taers232c** [comment]
I broke something; here's a solution.

gam.exe config csv_output_row_filter "meeting_code:regex:^[A-Z]" redirect csv  D:\0-IN\Analyse_Meet\meet_details_man.csv column_delimiter ";" report meet range 2020-10-05 2020-10-06

**Comment by taers232c** [comment]
This should be fixed in 5.22.02

Ross

**Comment by dav1303** [comment]
Thanks a lot

Your workaround works fine
