### ISSUE TITLE
"gam print org fromparent 'leaf node' showparent" fails with "API access Denied" when orgunit path does not have a child, if API scope is readonly

### ISSUE THREAD

**Issue by richardwadsworth** [taers232c/GAMADV-XTD3#96]
Calling "gam print org fromparent showparent" for an org unit that is a leaf i.e. does not have a child org unit, fails if the oauth2 scope is https://www.googleapis.com/auth/admin.directory.orgunit.readonly.  The same call succeeds if the scope is https://www.googleapis.com/auth/admin.directory.orgunit.

i.e.  this fails if the scope is readonly "gam print org fromparent 'leaf node' showparent"

Failing in version GAMADV-XTD3 5.22.07

**Comment by taers232c** [comment]
Will be fixed shortly in 5.22.08
