### ISSUE TITLE
Cloud Identity Devices calls failing with AttributeError

### ISSUE THREAD

**Issue by richardwadsworth** [taers232c/GAMADV-XTD3#97]
Any call to "gam print devices" or "gam info device" fails with the following error:

Traceback (most recent call last):
  File "gam.py", line 48514, in ProcessGAMCommand
  File "gam.py", line 17501, in doPrintCIDevices
AttributeError: 'NoneType' object has no attribute 'devices'

e.g. these both fail

gam info device XXXX7f05-c7c9-4c2e-b2e9-499e8a459XXX 

gam info device XXXX7f05-c7c9-4c2e-b2e9-499e8a459XXX 

Failing in version GAMADV-XTD3 5.22.07

**Comment by taers232c** [comment]
Richard,

Call me on Hangouts/Meet/Zoom.

ross.scroggs@gmail.com

Ross

**Comment by taers232c** [comment]
Have you done: gam user user@domain.com check serviceaccount
All device access is done via service account

**Comment by taers232c** [comment]
Will be fixed shortly in 5.22.08

**Comment by richardwadsworth** [comment]
Hi Ross.  

My error.  The service account had not been set up correctly as you suspected.  Too much tinkering.  Perhaps a more targeted error message would be useful.

Thanks for the pointer.
