### ISSUE TITLE
Provide additional Sync options for User Licenses

### ISSUE THREAD

**Issue by stephengale801** [taers232c/GAMADV-XTD3#98]
Group membership sync includes several helpful options such as 
```
        [addonly|removeonly] [notsuspended|suspended] [preview] [actioncsv]
```
With the existing limitations on the License API, namely Queries per second/day, being able to perform these advanced actions with GAM without calling the API would be extremely helpful

REF:
https://github.com/taers232c/GAMADV-XTD3/wiki/Groups-Membership#synchronize-members-in-a-group
https://github.com/taers232c/GAMADV-XTD3/wiki/Users-Licenses#synchronize-licenses

**Comment by taers232c** [comment]
I don't understand the request, call me on Hangouts/Meet/Zoom.

ross
ross.scroggs@gmail.com

**Comment by taers232c** [comment]
Done. 5.23.00
